Киборги Службы Безопасности
space-syndicate/space-station-14-next pull request #100
Opened 2024-11-30 20:32 UTC by ASTRALIXIX

## Описание PR
Добавлены борги службы безопасности в выбор конфигурации боргов.  

- Добавление нового типа шасси (Присутствует ограничение в максимум 3 модуля). Добавление новых 4 модулей для него.
- Всё открывается в ветке арсенала РНД и создаётся в ТехФабе СБ.
- Добавление новых само-перезаряжаемых версий снаряжения СБ. (Стяжек нету в угоду баланса) 
- Борг идёт как отличная поддержка в отделе, но явно не замена полноценному офицеру (Из-за отсутствия стяжек). Ещё добавлен портативный монитор криминальных записей и двойная дубинка-шокер в некоторые модули.

Модули:

- Обычный обезвреживающий (Станбатон на 5 ударов, Станнер на 5 выстрелов, Вспышка)
~~Лектер модуль (Установка разрешена только в КК, ну или в ЧС) (Лектер на 16 выстрелов и боевой нож)~~
- Защитный модуль (МК59 и боевой нож) Т2 Арсенал
- Контролирующий модуль (Вспомогательные приспособления) (ПМКЗ, Пульт от шлюзов, шприц, голопроектор) 
Т1 Арсенал
- Продвинутый обезвреживающий (Двойной Станбатон, Станнер пулемёт, Вспышка) Т2 Арсенал

## Почему / Баланс

Раз сейчас есть возможность менять законы абсолютно всем боргам на станции, а не только ИИ эти борги могут внести приятное дополнение к стороне синтетиков в случае чего (Или их восстания XD). Ну или просто помогать против антагонистов если они будут слишком сильными.

## Технические детали
Изменены yml файлы с энергетическим оружием, типами боргов, их шасси и добавлены новые папки в _CorvaxNext.
Присутствует полная локализация и на английский (Хз зачем)

## Медиа
![modules](https://github.com/user-attachments/assets/7dd70f71-8dc6-48e8-b58d-2bf04f81ff24)
![menu](https://github.com/user-attachments/assets/b3bd88a4-5785-4a19-a9c1-e82dfbb8adc9)

## Критические изменения
Неа

**Список изменений**
:cl:
- add: Добавлены борги службы безопасности
- add: Добавлены 4 новых модуля в технологической ветке арсенала и в ТехФабе СБ
- add: Добавлены Портативный монитор криминальных записей и Двойной станбатон (Только в продвинутом модуле)

2024-11-30 20:56 UTC, lzk228 commented
я закрою это
в сс14 не нужны борги сб

2024-11-30 21:14 UTC, Morp9x commented
Дизбалансный ПР, вы можете спокойно уничтожить борга при помощи кирки(у боргов нет резиста от структурного урона) и заполучить самую лучшую поддержку агента синдиката за 8 тк.

2024-11-30 21:49 UTC, Moryachok136 commented
Описание модулей поподробнее бы увидеть.
Лектер слишком сильно звучит,  дать что-то послабее или убрать вообще.
Может двустволка с пулями?

2024-11-30 21:51 UTC, Moryachok136 commented
> я закрою это
> 
> в сс14 не нужны борги сб

Почему нет то? У него могут сломаться законы, его могут взломать, он хрупкий.
Единственное что реально имба - наличие лектер модуля.

2024-11-30 21:52 UTC, Moryachok136 commented
> Дизбалансный ПР, вы можете спокойно уничтожить борга при помощи кирки(у боргов нет резиста от структурного урона) и заполучить самую лучшую поддержку агента синдиката за 8 тк. 

Борг скорее всего отобьется / успеет доложить

2024-11-30 22:06 UTC, Morp9x commented
> > Дизбалансный ПР, вы можете спокойно уничтожить борга при помощи кирки (у боргов нет резиста от структурного урона) и заполучить лучшую поддержку агента синдиката за 8 тк.
> 
> Борг скорее всего отобьется / успеет доложить. Надо хитростью

Хитрость тут не нужна, если вы совсем огузок, то всегда можно купить за 2 тк ЕМА гранату, который отключит у него рацию. Да на крайняк можно сказать "пошли, я тебе новые модули поставлю" и всё.

2024-12-01 04:52 UTC, ASTRALIXIX commented
> Описание модулей поподробнее бы увидеть. Лектер слишком сильно звучит, дать что-то послабее или убрать вообще. Может двустволка с пулями?

Полагаю можно, если это действительно слишком уж сильно

2024-12-01 04:53 UTC, ASTRALIXIX commented
> > > Дизбалансный ПР, вы можете спокойно уничтожить борга при помощи кирки (у боргов нет резиста от структурного урона) и заполучить лучшую поддержку агента синдиката за 8 тк.
> > 
> > 
> > Борг скорее всего отобьется / успеет доложить. Надо хитростью
> 
> Хитрость тут не нужна, если вы совсем огузок, то всегда можно купить за 2 тк ЕМА гранату, который отключит у него рацию. Да на крайняк можно сказать "пошли, я тебе новые модули поставлю" и всё.

И по итогу ты потратишь 10 ТК на борга с дубинкой и станнером. Не думаю, что это слишком имбалансно

2024-12-02 09:07 UTC, CaptainSqrBeard commented
В сс13 подобных боргов убрали со множества серверов (как МРП, так и ЛРП) из-за того, сколько они проблем приносили другим игрокам и модераторам постоянными нарушениями законов. Вполне вероятно, что мы столкнёмся с той-же проблемой. Даже у оффов схожий модуль секборгов отклонили по тем-же причинам.

Можно добавить в качестве альтернативы Peacemaker-a. У него есть инструменты лишь для предотвращения хуман харма, но не для ведения полноценного боя

скриншот с вики для вдохновения:
![изображение](https://github.com/user-attachments/assets/9b6d1dbe-aef0-42c0-b4bb-f2ee78ad8451)

2024-12-02 12:04 UTC, ASTRALIXIX commented
> В сс13 подобных боргов убрали со множества серверов (как МРП, так и ЛРП) из-за того, сколько они проблем приносили другим игрокам и модераторам постоянными нарушениями законов. Вполне вероятно, что мы столкнёмся с той-же проблемой. Даже у оффов схожий модуль секборгов отклонили по тем-же причинам.
> 
> Можно добавить в качестве альтернативы Peacemaker-a. У него есть инструменты лишь для предотвращения хуман харма, но не для ведения полноценного боя
> 
Полагаю это вполне себе имеет смысл, но я бы посмотрела на них хотя бы в тестовом виде. Ну, а так может и лучше реализовать Peacemaker-ов

2024-12-02 12:08 UTC, ASTRALIXIX commented
> Лучше вообще убрать Лектер модуль, в частности боевой. Если борг СБ и будет, то только со средствами обезвреживания, а не убийства.

То есть абсолютно убрать боевой модуль как таковой?

2024-12-02 12:34 UTC, CatBackGround requested changes
Чиним YAML Linter.

2024-12-02 12:34 UTC, CatBackGround commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  noSpawn: true
Используй categories: `categories: [ HideSpawnMenu ]` вместо `noSpawn: true`

2024-12-02 12:34 UTC, CatBackGround commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
> +  noSpawn: true
Используй categories: `categories: [ HideSpawnMenu ]` вместо `noSpawn: true`

2024-12-02 12:34 UTC, CatBackGround commented on Resources/Prototypes/Entities/Objects/Weapons/security.yml
> +  noSpawn: true
Используй categories: `categories: [ HideSpawnMenu ]` вместо `noSpawn: true`

2024-12-02 12:34 UTC, CatBackGround commented on Resources/Prototypes/_CorvaxNext/Entities/Objects/Tools/HandheldComputers/handheld_criminal_Records.yml
> +  noSpawn: true
Используй categories: `categories: [ HideSpawnMenu ]` вместо `noSpawn: true`

2024-12-02 12:38 UTC, CatBackGround commented on Resources/Locale/ru-RU/borg/borg.ftl
> +borg-type-security-name = Служебный
Предложу использовать вместо  **Служебный** слово **Охранный**

2024-12-02 13:08 UTC, ASTRALIXIX commented on Resources/Locale/ru-RU/borg/borg.ftl
> +borg-type-security-name = Служебный
Благодарю

2024-12-02 17:19 UTC, ASTRALIXIX commented
Лектер модуль был полностью удалён и изменён на модуль с самозарядным МК58. И все фиксы сделаны

2024-12-03 15:58 UTC, Nimfar11 commented
> Лектер модуль был полностью удалён и изменён на модуль с самозарядным МК58. И все фиксы сделаны

А чего огнестрельное оружие выбрал? Может лазерное дать? По мощности может как пистолет Сваллин, только зарядов побольше. Ну или мощнее лазер.  Против тех же ЯО будет даже полезнее, ведь можно будет держать дистанцию чтобы не отхватить от ЭМИ.

2024-12-03 20:19 UTC, Moryachok136 commented
> > > Лектер модуль был полностью удалён и изменён на модуль с самозарядным МК58. И все фиксы сделаны
> > 
> > 
> > А чего огнестрельное оружие выбрал? Может лазерное дать? По мощности может как пистолет Сваллин, только зарядов побольше. Ну или мощнее лазер. Против тех же ЯО будет даже полезнее, ведь можно будет держать дистанцию чтобы не отхватить от ЭМИ.
> 
> Вероятно, это будет более балансно. Хотя под сомнением

На Т3 нормально думаю будет. На обычные режимы нечасто встретишь, на нюку много боргов не сделают

2024-12-05 12:09 UTC, CatBackGround approved these changes
Всё чисто. Но нужно смотреть Checks.

2024-12-06 02:59 UTC, AwareFoxy requested changes
Переделать в PeaceMaker'а из 13 станции.

2024-12-06 03:07 UTC, FireNameFN requested changes

2024-12-06 03:07 UTC, FireNameFN commented on Resources/Locale/ru-RU/_CorvaxNext/entities/objects/Robotics/security.ftl
Замени `_CorvaxNext` на `_corvaxnext`.

2024-12-06 09:54 UTC, ASTRALIXIX commented on Resources/Locale/ru-RU/_CorvaxNext/entities/objects/Robotics/security.ftl
o7

2024-12-06 10:02 UTC, ASTRALIXIX commented
Ладно видимо придётся полностью с нуля писать других боргов... ну ладно

2024-12-06 12:10 UTC, ASTRALIXIX commented
> Переделать в PeaceMaker'а из 13 станции.

Это борг абсолютно другого плана

2024-12-11 05:59 UTC, closed without merging