Night and thermal vision device
space-syndicate/space-station-14-next pull request #104
Opened 2024-12-01 11:25 UTC by pofitlo-Git

## Описание PR

Порт приборов ночного и термального зрения с ВД 
https://github.com/WWhiteDreamProject/wwdpublic/pull/89

Острый вопрос обстоит с балансом и геймдизайном этих приборов. вполне желательно их пересмотреть 

## Медиа

![2024-12-01_12-49-08](https://github.com/user-attachments/assets/e9b99674-8188-410d-928c-846110c8051c)
![2024-12-01_12-48-46](https://github.com/user-attachments/assets/2721eba9-cc89-4e14-81b0-515937358252)
![2024-12-01_12-49-38](https://github.com/user-attachments/assets/5959848a-7ae6-44cf-ab4d-4a4dd0ce7296)
![2024-12-01_13-57-44](https://github.com/user-attachments/assets/e4e1dddd-a218-4ecc-aa2d-89561674a597)

**Список изменений**

- Прибор ночного зрения - позволяет видеть в кромешной темноте
- Прибор термального зрения - позволяет видеть живых существ за стенами
- Доступны агентам за 6 и 8 ТК
- Доступны ЯО за 10 и 12 ТК соответственно.

2024-12-01 11:44 UTC, AwareFoxy commented
не буду ревьювить со сломанными тестами

2024-12-01 13:34 UTC, FireNameFN requested changes
А ещё комментарии в некоторых файлах неправильные.

2024-12-01 13:34 UTC, FireNameFN commented on Content.Client/_CorvaxNext/Overlays/BaseSwitchableOverlay.cs
> +            return;
Кхм.

2024-12-01 13:34 UTC, FireNameFN commented on Content.Client/_CorvaxNext/Overlays/BaseSwitchableOverlay.cs
> +            || _player.LocalEntity == null
```suggestion
            || _player.LocalEntity is null
```

2024-12-01 13:34 UTC, FireNameFN commented on Content.Client/_CorvaxNext/Overlays/ThermalVisionOverlay.cs
> +            return;
Тоже.

2024-12-01 13:34 UTC, FireNameFN commented on Content.Client/_CorvaxNext/Overlays/ThermalVisionOverlay.cs
> +            || _players.LocalEntity == null
```suggestion
            || _players.LocalEntity is null
```

2024-12-01 13:34 UTC, FireNameFN commented on Content.Client/_CorvaxNext/Overlays/ThermalVisionOverlay.cs
> +        if (eye == null)
```suggestion
        if (eye is null)
```

2024-12-01 13:34 UTC, FireNameFN commented on Content.Client/_CorvaxNext/Overlays/ThermalVisionOverlay.cs
> +                    && _entity.TryGetComponent<TransformComponent>(owner, out var ownerXform))
На ранний выход.

2024-12-01 13:37 UTC, pofitlo-Git commented on Content.Client/_CorvaxNext/Overlays/ThermalVisionOverlay.cs
> +            return;
решите это между вами. я не хочу как в прошлом моем ПРе по 3 раза собирать-разбирать эту систему

2024-12-01 21:23 UTC, AwareFoxy requested changes

2024-12-01 21:23 UTC, AwareFoxy commented on Content.Shared/_CorvaxNext/Clothing/Components/ClothingGrantComponentComponent.cs
> +        [DataField("component", required: true)]
```suggestion
        [DataField(required: true)]
```

2024-12-01 21:23 UTC, AwareFoxy commented on Content.Shared/_CorvaxNext/Clothing/Components/ClothingGrantTagComponent.cs
> +    [DataField("tag", required: true), ViewVariables(VVAccess.ReadWrite)]
```suggestion
    [DataField(required: true), ViewVariables(VVAccess.ReadWrite)]
```

Если я не ошибаюсь, ReadWrite по умолчанию стоит в датафилдах.

2024-12-01 21:23 UTC, AwareFoxy commented on Resources/Locale/en-US/research/technologies.ftl
> +research-technology-night-vision = Night vision
в отдельный .ftl файл

2024-12-01 21:23 UTC, AwareFoxy commented on Resources/Locale/ru-RU/_corvaxnext/research/technologies.ftl
> +research-technology-night-vision = Ночное видение
в отдельную фтлку

2024-12-01 21:23 UTC, AwareFoxy commented on Resources/Prototypes/_CorvaxNext/Research/experimental.yml
> +  id: NightVisionTech
в отдельный .yml, в Т3

2024-12-02 03:24 UTC, CaptainSqrBeard requested changes

2024-12-02 03:24 UTC, CaptainSqrBeard commented on Resources/Locale/ru-RU/_CorvaxNext/entities/clothing/eyes/goggles.ftl
> +ent-ClothingEyesNightVisionGoggles = ПНВ
напиши без сокращения

2024-12-02 03:24 UTC, CaptainSqrBeard commented on Resources/Locale/ru-RU/_CorvaxNext/entities/clothing/eyes/goggles.ftl
> +ent-ClothingEyesThermalVisionGoggles = ПТВ
тут тоже

2024-12-02 03:33 UTC, CaptainSqrBeard requested changes

2024-12-02 03:33 UTC, CaptainSqrBeard commented on Content.Shared/Body/Components/BodyComponent.cs
> +    public bool ThermalVisibility = true;
это стоило реализовать через отдельный компонент, а не через поле в `BodyComponent`

2024-12-04 08:46 UTC, Seven2280 commented
Стоит понизить цену в аплинке до 2 тк у пнв и 3 тк у термалов

2024-12-05 19:27 UTC, Vonsant commented
> У ВВДП сейчас тёрки с Санрайзом. Не мерджить.

Должны ли нас волновать их разборки при agpl коде?

2024-12-09 04:21 UTC, AwareFoxy requested changes

2024-12-09 04:21 UTC, AwareFoxy commented on Resources/Locale/ru-RU/_CorvaxNext/entities/clothing/eyes/goggles.ftl
> +ent-ClothingEyesNightVisionGoggles = Прибор ночного видения
```suggestion
ent-ClothingEyesNightVisionGoggles = прибор ночного видения
```

2024-12-09 04:21 UTC, AwareFoxy commented on Resources/Locale/ru-RU/_CorvaxNext/entities/clothing/eyes/goggles.ftl
> +ent-ClothingEyesThermalVisionGoggles = Прибор термального видения
```suggestion
ent-ClothingEyesThermalVisionGoggles = прибор термального видения
```

2024-12-09 04:21 UTC, AwareFoxy commented on Resources/Prototypes/_CorvaxNext/Catalog/uplink_catalog.yml
> +    Telecrystal: 6
```suggestion
    Telecrystal: 10
```

2024-12-09 04:21 UTC, AwareFoxy commented on Resources/Prototypes/_CorvaxNext/Catalog/uplink_catalog.yml
> +    Telecrystal: 8
```suggestion
    Telecrystal: 12
```

2024-12-09 04:26 UTC, AwareFoxy approved these changes

2024-12-09 04:40 UTC, AwareFoxy commented
жду предложку "удалить термалы" через 24 часа после мерджа

2024-12-09 04:41 UTC, merged

2024-12-09 04:41 UTC, pofitlo-Git commented
сюдааааа

2024-12-09 04:42 UTC, pofitlo-Git commented
плевать не термалы, лол. мне нужен был BaseSwitchableOverlay. 
резооомки теперь будут с ещё одной способностью~~~

2024-12-09 08:15 UTC, Vonsant commented on Resources/Prototypes/Entities/Mobs/Player/admin_ghost.yml
> +  - type: ThermalInvisibility #Corvax-Next-ThermalVision
А обычным гостам почему не добавили?

2024-12-09 08:30 UTC, FireNameFN commented
Ну и фигня там шейдеры. Кто-то записывать геймплей будет - умрёт.

2024-12-09 16:29 UTC, pofitlo-Git commented on Resources/Prototypes/Entities/Mobs/Player/admin_ghost.yml
> +  - type: ThermalInvisibility #Corvax-Next-ThermalVision
Я без понятия зачем это вообще гостам добавлять, на которых и так не действуют термалы. Но оно было, я оставил. ХЗ