Открытие шлюзов всегда сохраняет отпечатки.
space-syndicate/space-station-14-next pull request #112
Opened 2024-12-02 19:11 UTC by Vonsant

## Описание PR
Раньше шлюзы сохраняли отпечатки пальцев только если по ним прямо ткнуть мышкой. Если просто проходить сквозь них, то ничего не сохранялось.

Теперь при открытии шлюза тушкой (что подразумевает, что вы типа открываете шлюз рукой) отпечатки пальцев так же сохраняются на двери и могут быть просканированы анализатором детектива. Прохождение через уже открытый шлюз не сохраняет отпечатки.

## Почему / Баланс

Потому что текущее состояние этой системы, требующее именно нажатия на дверь мышкой для сохранения отпечатков - бред.

**Список изменений**

:cl:
- tweak: Все шлюзы теперь всегда сохраняют отпечатки пальцев (или тип перчаток) при их открытии проходом через них, а не только когда по ним жмешь курсором для открытия.

2024-12-02 19:16 UTC, FireNameFN requested changes
Не уверен на счёт юсингов и зависимостей, но Start и End исправь.

2024-12-02 19:16 UTC, FireNameFN commented on Content.Server/Doors/Systems/DoorSystem.cs
> +using Content.Server.Forensics; // Corvax-Next-DoorForensics
```suggestion
using Content.Server.Forensics;
```
Не стоит в юсингах.

2024-12-02 19:16 UTC, FireNameFN commented on Content.Server/Doors/Systems/DoorSystem.cs
> +	// Corvax-Next-DoorForensics start
```suggestion
	// Corvax-Next-DoorForensics-Start
```

2024-12-02 19:16 UTC, FireNameFN commented on Content.Server/Doors/Systems/DoorSystem.cs
> +	// Corvax-Next-DoorForensics end
```suggestion
	// Corvax-Next-DoorForensics-End
```

2024-12-02 19:16 UTC, FireNameFN commented on Content.Server/Doors/Systems/DoorSystem.cs
> +    [Dependency] private readonly ForensicsSystem _forensicsSystem = default!; // Corvax-Next-DoorForensics
В зависимостях тоже не рекомендую комментарии.

2024-12-02 21:23 UTC, AwareFoxy approved these changes
код просто пиздец

2024-12-02 21:23 UTC, merged

2024-12-02 21:33 UTC, Vonsant commented
> код просто пиздец

А чо тогда не поправишь?

2024-12-03 20:20 UTC, Olexiy-Lapin commented
Лол, а почему не оффам?

2024-12-03 21:13 UTC, Vonsant commented
> Лол, а почему не оффам?

А у них этот пр висит с пятого апреля открытым.