HideAndSeek
space-syndicate/space-station-14-next pull request #115
Opened 2024-12-03 12:40 UTC by Vonsant

## Описание PR

Сумки, рюкзаки и прочие мешки теперь можно прятать под плитками пола. Для этого необходимо снять напольную плитку и гаечным ключом прикрутить сумку, после чего положить поверх плитку. В меди на скриншоте всё будет понятно описано.

Спрятаные под полом сумки видно на т-лучевом сканере. Так же, два таких сканера добавлены в шкафчик детектива.

## Почему / Баланс

Преступления это весело.

## Ссылка на ветку

https://discord.com/channels/919301044784226385/1307344811933831241

## Медиа

![image](https://github.com/user-attachments/assets/8c6d1dbf-dc45-4745-ad7a-5368afe98048)

## Критические изменения

N/A - система самодостаточна и не изменяет сторонние файлы кода.

**Список изменений**

:cl:
- add: Сумки теперь можно прятать под плитками пола!

2024-12-03 15:08 UTC, FireNameFN requested changes

2024-12-03 15:08 UTC, FireNameFN commented on Resources/Prototypes/Entities/Clothing/Back/backpacks.yml
> +    # Corvax-Next-Stashes Start
```suggestion
    # Corvax-Next-Stashes-Start
```

2024-12-03 15:08 UTC, FireNameFN commented on Resources/Prototypes/Entities/Clothing/Back/backpacks.yml
> +    # Corvax-Next-Stashes End
```suggestion
    # Corvax-Next-Stashes-End
```

2024-12-03 15:08 UTC, FireNameFN commented on Content.Server/_CorvaxNext/Storage/AnchorableStorageSystem.cs
> +            _xform.Unanchor(ent, Transform(ent));
Дублирование Transform().

2024-12-03 15:12 UTC, FireNameFN commented
А ещё никакие сканеры в шкаф детектива не добавляли.

2024-12-03 15:30 UTC, Vonsant commented on Content.Server/_CorvaxNext/Storage/AnchorableStorageSystem.cs
> +            _xform.Unanchor(ent, Transform(ent));
Так и должно быть, иначе - не работает.

2024-12-03 15:33 UTC, Vonsant commented on Content.Server/_CorvaxNext/Storage/AnchorableStorageSystem.cs
> +            ).ToList();
Крашится при билде после замены.

2024-12-03 22:47 UTC, FireNameFN commented
Сделал что-то, протестируйте. Возможно, всё сломал.

2024-12-04 07:28 UTC, FireNameFN approved these changes

2024-12-04 07:32 UTC, merged

2024-12-04 07:32 UTC, Vonsant commented
> Сделал что-то, протестируйте. Возможно, всё сломал.

Работает.

2024-12-09 14:44 UTC, ZaArturSharkRUS1 reviewed
КЛАССНО!!!