The return of the Gate
space-syndicate/space-station-14-next pull request #131
Opened 2024-12-06 16:40 UTC by SeveringBaton

## Описание PR
Добавление **Gate** обратно в игру.

## Изменения 
- Добавление Gate

- Теперь на Gate есть **ЦИИ**

- Добавлен новый год

## Медиа
![{40502B6E-4F62-4CF8-A41E-8DE4613C6E98}](https://github.com/user-attachments/assets/41269f8f-18b5-4ffe-b597-a32181fc7643)
![{576F9875-3D8E-4CDE-B3EF-3F92FF4747B7}](https://github.com/user-attachments/assets/fd9b895a-5d02-40bc-a95f-22001cde3291)
![{C08EC0F6-ABA5-4BFB-A9B7-42754EA06D83}](https://github.com/user-attachments/assets/07bca01c-9537-4d47-a9cf-58e03beb12fb)

## Требования
 

- [X] Я прочитал(а) и следую [Рекомендациям по оформлению Pull Request и Changelog](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).

 

- [X] Я добавил(а) медиафайлы к этому PR или он не требует демонстрации в игре.

Список изменений

🆑 SeveringBaton12 

add: Станция Gate
tweak: Добавление ЦИИ на Gate
tweak: Добавление новогодних украшений на Gate

2024-12-06 17:44 UTC, NotSoDana commented
1) А автор карты вкурсе что его наработки без его ведома юзают? (Лицо Эда уже представляю)
2) Поддерживать карту и подгонять её под действующие мапперские стандарты кто будет? Читаем https://discord.com/channels/919301044784226385/1310876913388228628/1310877258415870003
3) Не смущает? https://github.com/space-wizards/space-station-14/pull/32032

2024-12-06 18:35 UTC, AwareFoxy approved these changes

2024-12-06 19:19 UTC, Ko4ergaPunk commented
CableHVUncuttable???

2024-12-06 20:09 UTC, AwareFoxy commented
> CableHVUncuttable???

наверн что б ИИ не отрезали

2024-12-06 20:10 UTC, Ko4ergaPunk requested changes
Короче, бегло прошелся по карте. Прошу внимательней проверить по чек-листу, ибо я уже сходу обнаружил, что у утилей стоит консоль экспедиций, и нет управления шаттлом. Оппорозидона тоже нет. В хирургии нет канистры. Дальше проверять не стал. 
Локализация что Подстанций, что камер, отсутствует. СМЭС не переименованы. Варп поинты не переименованы.
Используются странные объекты, по типу какого-то неразрушаемого ВВ кабеля. Новые новогодние ёлки замени на дефолтные. Наши неразрушаемы.
Debug ЛКП где-то еще валяется. Не нашел по кордам.
В сумме, на карте 6 ёлок с подарками. Максимум одна.
~35 коробок с подарками. У нас максимум по одному на пять человек.
В общем, работы над картой еще предстоит не мало.
Задуматься о добавлении в маппул можно только после оф релиза от Эда [#32032](https://github.com/space-wizards/space-station-14/pull/32032). Когда Emisse проведет ревью, а Эд пофиксит недочеты. Иначе тратить на это силы бессмысленно. Плюс ждем мержа ПРов из TODO.

Исправь критические недочеты, и после этого можешь толкать через кастом голосование, но никак не в маппул. Даже в таком случае, только после 14-го числа. У нас на эту дату назначен переход карт с зимнего сезона на праздничный. Еще напомню, что судьба оффовских карт на Нексте все еще туманна.
Пожалуйста, не стесняйся задавать вопросы в ЛС, чтобы подобное больше не повторялось.

2024-12-06 20:18 UTC, Vonsant commented
> 1. А автор карты вкурсе что его наработки без его ведома юзают? (Лицо Эда уже представляю)
> 2. Поддерживать карту и подгонять её под действующие мапперские стандарты кто будет? Читаем https://discord.com/channels/919301044784226385/1310876913388228628/1310877258415870003
> 3. Не смущает? [Gate map space-wizards/space-station-14#32032](https://github.com/space-wizards/space-station-14/pull/32032)
> 4. ПР говна с технической части. Можно было бы хотя бы поинтересоваться сначала как работает добавление карт, а уже потом в гит лезть

Кто тараканов в комментарии некста пустил?

2024-12-06 20:19 UTC, Vonsant commented
![image](https://github.com/user-attachments/assets/f8beb174-68d0-4873-814c-dbc79b96b574)
Брысь, а то я не побоюсь его использовать.

2024-12-06 20:30 UTC, NotSoDana commented
> 
> Кто тараканов в комментарии некста пустил?
Я пришла на зов щитмаппинга и кринжа

2024-12-07 05:45 UTC, foboscheshir commented
быть добру

2024-12-07 07:26 UTC, YuiFann commented
> Короче, бегло прошелся по карте. Прошу внимательней проверить по чек-листу, ибо я уже сходу обнаружил, что у утилей стоит консоль экспедиций, и нет управления шаттлом. Оппорозидона тоже нет. В хирургии нет канистры. Дальше проверять не стал. Локализация что Подстанций, что камер, отсутствует. СМЭС не переименованы. Варп поинты не переименованы. Используются странные объекты, по типу какого-то неразрушаемого ВВ кабеля. Новые новогодние ёлки замени на дефолтные. Наши неразрушаемы. Debug ЛКП где-то еще валяется. Не нашел по кордам. В сумме, на карте 6 ёлок с подарками. Максимум одна. ~35 коробок с подарками. У нас максимум по одному на пять человек. В общем, работы над картой еще предстоит не мало. Задуматься о добавлении в маппул можно только после оф релиза от Эда [#32032](https://github.com/space-wizards/space-station-14/pull/32032). Когда Emisse проведет ревью, а Эд пофиксит недочеты. Иначе тратить на это силы бессмысленно. Плюс ждем мержа ПРов из TODO.
> 
> Исправь критические недочеты, и после этого можешь толкать через кастом голосование, но никак не в маппул. Даже в таком случае, только после 14-го числа. У нас на эту дату назначен переход карт с зимнего сезона на праздничный. Еще напомню, что судьба оффовских карт на Нексте все еще туманна. Пожалуйста, не стесняйся задавать вопросы в ЛС, чтобы подобное больше не повторялось.

ты что тут забыл? это репа для крутых

2024-12-11 01:06 UTC, Awlod commented
> Короче, бегло прошелся по карте. Прошу внимательней проверить по чек-листу, ибо я уже сходу обнаружил, что у утилей стоит консоль экспедиций, и нет управления шаттлом. Оппорозидона тоже нет. В хирургии нет канистры. Дальше проверять не стал. Локализация что Подстанций, что камер, отсутствует. СМЭС не переименованы. Варп поинты не переименованы. Используются странные объекты, по типу какого-то неразрушаемого ВВ кабеля. Новые новогодние ёлки замени на дефолтные. Наши неразрушаемы. Debug ЛКП где-то еще валяется. Не нашел по кордам. В сумме, на карте 6 ёлок с подарками. Максимум одна. ~35 коробок с подарками. У нас максимум по одному на пять человек. В общем, работы над картой еще предстоит не мало. Задуматься о добавлении в маппул можно только после оф релиза от Эда [#32032](https://github.com/space-wizards/space-station-14/pull/32032). Когда Emisse проведет ревью, а Эд пофиксит недочеты. Иначе тратить на это силы бессмысленно. Плюс ждем мержа ПРов из TODO.
> 
> Исправь критические недочеты, и после этого можешь толкать через кастом голосование, но никак не в маппул. Даже в таком случае, только после 14-го числа. У нас на эту дату назначен переход карт с зимнего сезона на праздничный. Еще напомню, что судьба оффовских карт на Нексте все еще туманна. Пожалуйста, не стесняйся задавать вопросы в ЛС, чтобы подобное больше не повторялось.

На боксе также нет консоль управления утильским шаттлом, исправляем? 🐱‍👤

2024-12-17 09:53 UTC, TheShuEd commented
Моё лицо:
![image](https://github.com/user-attachments/assets/d60ee017-d47a-4406-9c7e-8b6688089a18)

2024-12-17 09:54 UTC, TheShuEd commented
Не, ну удачи вам поддерживать это параллельно
там на карте столько говна накопилось, которое вычищать еще оч долго

2024-12-17 16:56 UTC, kosticia commented
Пока оффы не рассмотрят консоль управления гейтами эта карта будет не сильно функциональна

2025-01-11 15:32 UTC, closed without merging