Something for testing
space-syndicate/space-station-14-next pull request #132
Opened 2024-12-07 00:44 UTC by Vonsant

## Описание PR

## Почему / Баланс

## Ссылка на ветку

## Технические детали

## Медиа

## Критические изменения

**Список изменений**

2024-12-07 01:05 UTC, FireNameFN requested changes
Не очень понял, что за ПР. Кажется, он добавляет сразу две механики. Ревью, как обычно, в основном по красоте кода, но посмотри на Dirty и нетворкинг.

2024-12-07 01:05 UTC, FireNameFN commented on Content.Server/_CorvaxNext/Implants/Radio/RadioImplantSystem.cs
> +            return;
И это бы разкрафтить.

2024-12-07 01:05 UTC, FireNameFN commented on Content.Server/_CorvaxNext/Implants/Radio/RadioImplantSystem.cs
> +            && radioImplantComponent.Channels.Contains(args.Channel.ID))
Инвертировать и разкрафтить.

2024-12-07 01:11 UTC, Vonsant commented on Content.Server/_CorvaxNext/Storage/EntitySystems/MouthStorageSystem.cs
> +            args.Message = _replacement.ApplyReplacements(args.Message, "mumble");
Это акцент, он заменяет все фразы на "мффпфф" и "пфмффф", он так везде используется, так что это трогать наверное не буду.

2024-12-07 11:37 UTC, Vonsant commented on Content.Shared/_CorvaxNext/Implants/Radio/SharedRadioImplantSystem.cs
> +        Dirty(component.Implantee.Value, hasRadioImplantComponent);
Отчет после проверки  - надо.

2024-12-07 11:39 UTC, Vonsant commented on Content.Shared/_CorvaxNext/Storage/EntitySystems/SharedMouthStorageSystem.cs
> +        base.Initialize();
При удалении его вызова всё падает с криками "Наташ вставай мы все уронили"

2024-12-07 11:40 UTC, Vonsant commented on Content.Shared/_CorvaxNext/Storage/Components/MouthStorageComponent.cs
> +    public FixedPoint2 SpitDamageThreshold = FixedPoint2.New(2);
Хз как это связано, но после этой замены выбить ничего из зубов уже не даёт.

2024-12-07 11:58 UTC, Vonsant commented on Content.Client/_CorvaxNext/Implants/Radio/RadioImplantSystem.cs
> +}
Для истории: Не работает, требует скобочки.

2024-12-07 22:37 UTC, AwareFoxy commented on Content.Shared/_CorvaxNext/Storage/Components/MouthStorageComponent.cs
> +    public FixedPoint2 SpitDamageThreshold = FixedPoint2.New(2);
Потому что оно создаёт объект FixedPoint2 с указанным значением, а 2 — просто возвращает

2024-12-07 22:39 UTC, AwareFoxy commented on Resources/Locale/ru-RU/ss14-ru/prototypes/_corvaxnext/actions/agility.ftl
> -ent-SwitchAgilityAction = Переключить ловкость.
Зачем удалять то? Это абилки резоми.

2024-12-07 23:44 UTC, Vonsant commented on Resources/Locale/ru-RU/ss14-ru/prototypes/_corvaxnext/actions/agility.ftl
> -ent-SwitchAgilityAction = Переключить ловкость.
Ачовсмысле, почему оно вообще зааффектилось

2024-12-09 14:21 UTC, CaptainSqrBeard commented
А по поводу предметов. Конечности, органы, пИИ, позитронные мозги и мозго-машинные интерфейсы не должны пихаться в рот.

2024-12-28 09:41 UTC, kosticia commented
А зачем вообще в cl писать про имплант?

2025-03-30 23:33 UTC, closed without merging

2025-03-31 00:07 UTC, FireNameFN commented
Никакого воре с Гамлетом.