[Port] Ghost Bar
space-syndicate/space-station-14-next pull request #136
Opened 2024-12-07 18:52 UTC by AwareFoxy

## Описание PR
Портирован призрачный бар с Goob Station

## Почему / Баланс
Для призраков

## Ссылка на ветку

## Технические детали

## Медиа

https://github.com/user-attachments/assets/9b27461b-34ac-43bc-9f13-3664d084d327

## Критические изменения

**Список изменений**

2024-12-07 19:42 UTC, Vonsant requested changes

2024-12-07 19:42 UTC, Vonsant commented on Content.Client/UserInterface/Systems/Ghost/Widgets/GhostGui.xaml.cs
> +    public GhostBarRulesWindow GhostBarWindow { get; }
// _Corvax

2024-12-07 19:42 UTC, Vonsant commented on Content.Client/UserInterface/Systems/Ghost/Widgets/GhostGui.xaml.cs
> +        GhostBarWindow = new GhostBarRulesWindow();
анал логичный

2024-12-07 19:42 UTC, Vonsant commented on Resources/Locale/ru-RU/_CorvaxNext/ghostbar/guidebook/ghost-gui.ftl
> +ghost-bar-rules = Относитесь к этой роли и станции так же, как к обычному Призраку. Вы можете говорить обо всех текущих событиях раунда без необходимости LOOC, и вы помните все из своей предыдущей жи
Бедная модерация при просмотре логов. И потом хер разберешь, обсуждал он IC в гостбаре или нет. Есть ли возможность добавлять к именам персонажей какой-нибудь префикс, чтобы потом по логам было точно видно, что перс в гостбаре?

2024-12-07 19:42 UTC, Vonsant commented on Resources/Locale/ru-RU/_CorvaxNext/ghostbar/guidebook/ghost-gui.ftl
> +ghost-window-spawn-ghostbar-button = Появится в баре
Появит**ь**ся

2024-12-07 19:42 UTC, Vonsant commented on Resources/Locale/ru-RU/_CorvaxNext/ghostbar/guidebook/ghost-gui.ftl
> +ghost-window-spawn-ghostbar-button-timer = Появится в баре через ({$time}с)
появит**ь**ся

2024-12-07 19:42 UTC, Vonsant commented on Resources/Locale/ru-RU/_CorvaxNext/ghostbar/guidebook/ghost-gui.ftl
> +ghost-bar-rules = Относитесь к этой роли и станции так же, как к обычному Призраку. Вы можете говорить обо всех текущих событиях раунда без необходимости LOOC, и вы помните все из своей предыдущей жи
Кому "помогите" то блять.
"сообщите в ахелп".

2024-12-07 19:42 UTC, Vonsant commented on Resources/Maps/_CorvaxNext/Nonstations/ghostbar.yml
> +    components:
Добавь еще компонент:
`    - type: ProtectedGrid`
чтобы не разрушали ничего

2024-12-07 19:42 UTC, Vonsant commented on Resources/Prototypes/Goobstation/Entities/Markers/Spawners/ghost_roles.yml
> +  name: ghost bar spawn point
Сделай локаль для этого спавнера.

2024-12-07 21:10 UTC, CaptainSqrBeard commented on Resources/Locale/ru-RU/_CorvaxNext/ghostbar/guidebook/ghost-gui.ftl
> +ghost-bar-rules = Относитесь к этой роли и станции так же, как к обычному Призраку. Вы можете говорить обо всех текущих событиях раунда без необходимости LOOC, и вы помните все из своей предыдущей жи
> Кому "помогите" то блять. "сообщите в ахелп".

ПОЖАЛУЙСТА ПОМОГИТЕ

2024-12-07 21:20 UTC, CaptainSqrBeard commented
# Тестирование
- Гостбар делает игроков невозрождаемыми. Если будешь это фиксить, я буду рад если эта система будет обобщённой.
- Кто такой Icepick в бумажке в баре?
- Я думаю лучше просто ограничить гриферскую активность в гостбаре. Тоесть отключить урон по игрокам, разрушаемость карты. На карте есть боксёрские перчатки, они должны продолжить работать. Тогда игрокам не придётся по приколу звать игроков в бар, если он OOC-шный.
- Объекты на карте можно удалять, забирая их и гостаясь.
- Объекты на карте можно бесконечно создавать, убирая их с персонажа и гостаясь

## Карта
- Атмос. Он реализован через механ (где-то там стоят трубы от генератора воздуха). Причём атмос не включен сразу же. В теории можно было-бы зафиксировать атмос, но я не знаю через какие компоненты это делается.
- На карте есть несколько тайлов сетки решётки, что являются другими гридами.
- Мусорка ведёт сразу-же в космос. Причём на том конце есть другая мусорка, и эта мусорка не имеет питания.
- Двери ограничены доступом. Думаю их стоило сделать с общим доступом.
- Карта и её грид(ы) не имеют названий, тяжело их распознать в админском списке.
- На карте есть шлюзы в космос, что не имеют вентиляторов под собой. Можно легко спустить всю атмосферу.
![изображение](https://github.com/user-attachments/assets/41e627e0-92d3-40fe-84a6-3aa2d6a17cfe)

2024-12-07 21:40 UTC, AwareFoxy commented on Content.Client/UserInterface/Systems/Ghost/Widgets/GhostGui.xaml.cs
> +    public GhostBarRulesWindow GhostBarWindow { get; }
```suggestion
    public GhostBarRulesWindow GhostBarWindow { get; }  // CorvaxNext-GhostBar
```

2024-12-07 21:41 UTC, CaptainSqrBeard commented on Content.Client/UserInterface/Systems/Ghost/Widgets/GhostGui.xaml.cs
> +    public GhostBarRulesWindow GhostBarWindow { get; }
он ревьювит свой же PR

2024-12-07 21:41 UTC, AwareFoxy commented on Content.Client/UserInterface/Systems/Ghost/Widgets/GhostGui.xaml.cs
> +    public event Action? GhostBarPressed; // _CorvaxNext - Ghost Bar
```suggestion
    public event Action? GhostBarPressed;  // CorvaxNext-GhostBar
```

2024-12-07 21:41 UTC, AwareFoxy commented on Content.Client/UserInterface/Systems/Ghost/Widgets/GhostGui.xaml.cs
> +        GhostBarWindow = new GhostBarRulesWindow();
```suggestion
        GhostBarWindow = new GhostBarRulesWindow();  // CorvaxNext-GhostBar
```

2024-12-07 21:41 UTC, AwareFoxy commented on Content.Client/UserInterface/Systems/Ghost/Widgets/GhostGui.xaml.cs
> +        GhostBarButton.OnPressed += _ => GhostBarPressed?.Invoke(); // _CorvaxNext - Ghost Bar
```suggestion
        GhostBarButton.OnPressed += _ => GhostBarPressed?.Invoke();  // CorvaxNext-GhostBar
```

2024-12-07 21:41 UTC, AwareFoxy commented on Content.Client/UserInterface/Systems/Ghost/Widgets/GhostGui.xaml.cs
> +        GhostBarWindow.Close(); // _CorvaxNext - Ghost Bar
```suggestion
        GhostBarWindow.Close();  // CorvaxNext-GhostBar
```

2024-12-07 21:41 UTC, AwareFoxy commented on Content.Client/UserInterface/Systems/Ghost/Widgets/GhostGui.xaml.cs
> +            GhostBarWindow.Dispose(); // _CorvaxNext - Ghost Bar
```suggestion
            GhostBarWindow.Dispose();  // CorvaxNext-GhostBar
```

2024-12-07 21:41 UTC, AwareFoxy commented on Resources/Locale/ru-RU/_CorvaxNext/ghostbar/guidebook/ghost-gui.ftl
> +ghost-window-spawn-ghostbar-button = Появится в баре
```suggestion
ghost-window-spawn-ghostbar-button = Появиться в баре
```

2024-12-07 21:41 UTC, AwareFoxy commented on Resources/Locale/ru-RU/_CorvaxNext/ghostbar/guidebook/ghost-gui.ftl
> +ghost-window-spawn-ghostbar-button-timer = Появится в баре через ({$time}с)
```suggestion
ghost-window-spawn-ghostbar-button-timer = Появиться в баре через ({$time}с)
```

2024-12-07 21:41 UTC, AwareFoxy commented on Resources/Locale/ru-RU/_CorvaxNext/ghostbar/guidebook/ghost-gui.ftl
> +ghost-bar-rules = Относитесь к этой роли и станции так же, как к обычному Призраку. Вы можете говорить обо всех текущих событиях раунда без необходимости LOOC, и вы помните все из своей предыдущей жи
```suggestion
ghost-bar-rules = Относитесь к этой роли и станции так же, как к обычному Призраку. Вы можете говорить обо всех текущих событиях раунда без необходимости LOOC, и вы помните все из своей предыдущей жизни. НЕ нападайте на других, не затевайте драк и не пытайтесь сломать станцию. Если вы увидите, что кто-то делает это, пожалуйста, сообщите в ахелп, и он будет немедленно выброшен в космос. Также, если вы решите покинуть бар, вы НЕ БУДЕТЕ помнить ничего из того, что было здесь, или из вашей предыдущей жизни.
```

2024-12-07 22:47 UTC, Vonsant commented on Resources/Locale/ru-RU/ss14-ru/prototypes/_corvaxnext/entities/spawners.ftl
> +ent-SpawnPointObserver = спавнер призрачный бар
GhostBarSpawner

2024-12-08 01:22 UTC, FireNameFN requested changes
ААААААААААААААААААААА

2024-12-08 01:22 UTC, FireNameFN commented on Resources/Locale/ru-RU/_CorvaxNext/ghostbar/guidebook/ghost-gui.ftl
ААААААААААААААААААААААААААААААА

2024-12-08 17:40 UTC, AwareFoxy commented on Resources/Locale/ru-RU/ss14-ru/prototypes/_corvaxnext/entities/spawners.ftl
> +ent-SpawnPointObserver = спавнер призрачный бар
```suggestion
ent-GhostBarSpawner = спавнер призрачный бар
```

2024-12-09 07:45 UTC, Vonsant commented
Ожидаем компетентной карты от @Ko4ergaPunk

2024-12-09 07:58 UTC, Vonsant commented
ETA - 2 недели.

2024-12-18 09:50 UTC, closed without merging