Подсветка текста в фильтрах QOL
space-syndicate/space-station-14-next pull request #14
Opened 2024-10-29 21:03 UTC by TokenStyle

## Описание PR
Подсветка в окне чата и пузырях сообщений слов выбранных для фильтра пользователем. Также доступна опция, автоматического заполнения подсветки в зависимости от роли и имени игрока (по умолчанию отключена, находится во вкладке параметров доступности, где также можно изменить цвет подсветки).

Слова, которые нужно подсвечивать, можно обернуть в кавычки " " для учета пробелов (или целых слов). Например, при вводе "Дек":

"**Дек**, приходи в бар" будет подсвечено. "Дектую свои правила" не будет подсвечено.
Взято с [PR 31442](https://github.com/space-wizards/space-station-14/pull/31442).

## Почему / Баланс
Это. Просто. Имба.
Функция давно присутствует на многих серверах SS13 и значительно улучшает читаемость сообщений, помогая отделам и отдельным игрокам быстрее понимать, когда их вызывают по радио.

## Технические детали
За деталями смотреть в первоисточник [PR 31442](https://github.com/space-wizards/space-station-14/pull/31442).

## Медиа
Настройки подсветки находятся в Параметры > доступность. Можно изменить цвет подсветки Цвет и другие параметры.

https://github.com/user-attachments/assets/79499721-7040-4835-a81c-328f59b0099a

## Требования

- [x] Я прочитал(а) и следую [Рекомендациям по оформлению Pull Request и Changelog](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] Я добавил(а) медиафайлы к этому PR или он не требует демонстрации в игре.

## Критические изменения

**Список изменений**

:cl:
- add: Теперь есть фильтр-подсветка сообщений в чате, в фильтрах!

2024-10-30 09:37 UTC, ksen0morph commented
это нам надо

2024-10-30 18:39 UTC, AwareFoxy requested changes
Поверхностно прошел по ЦВарам и тому что код не обернут в тэги, потом посмотрю сам код

2024-10-30 18:39 UTC, AwareFoxy commented on Content.Client/Options/UI/OptionsTabControlRow.xaml.cs
> +        return AddOption(new OptionColorSliderCVar(this, _cfg, cVar, slider));
в Corvax CVars

2024-10-30 18:39 UTC, AwareFoxy commented on Content.Client/Options/UI/Tabs/AccessibilityTab.xaml.cs
> +        Control.AddOptionCheckBox(CCVars.ChatAutoFillHighlights, AutoFillHighlightsCheckBox);
в Corvax CVars, закрой тэгами корвакса

2024-10-30 18:39 UTC, AwareFoxy commented on Content.Client/Options/UI/Tabs/AccessibilityTab.xaml.cs
> +        Control.AddOptionColorSlider(CCVars.ChatHighlightsColor, HighlightsColorSlider);
в Corvax CVars

2024-10-30 18:39 UTC, AwareFoxy commented on Content.Client/Options/UI/OptionsTabControlRow.xaml.cs
> +    /// <summary>
закрой тэгами по типу // Corvax-Highlights-Start // Corvax-Highlights-End // Corvax-Highlights

2024-10-30 18:39 UTC, AwareFoxy commented on Content.Client/Options/UI/OptionsTabControlRow.xaml.cs
> +/// <summary>
закрой тэгами корвакса

2024-10-30 18:39 UTC, AwareFoxy commented on Content.Client/Options/UI/Tabs/AccessibilityTab.xaml
> +                <CheckBox Name="AutoFillHighlightsCheckBox" Text="{Loc 'ui-options-auto-fill-highlights'}" />
закрой тэгами корвакса

2024-10-30 18:39 UTC, AwareFoxy commented on Content.Client/UserInterface/Systems/Chat/ChatUIController.cs
> +using Content.Client.CharacterInfo;
закрой тэгами корвакса, тоже самое со всеми изменениями в этом файле

2024-10-30 18:39 UTC, AwareFoxy commented on Content.Client/UserInterface/Systems/Chat/ChatUIController.cs
> +        _config.OnValueChanged(CCVars.ChatAutoFillHighlights, (value) => { _autoFillHighlightsEnabled = value; });
Corvax CVars

2024-10-30 18:39 UTC, AwareFoxy commented on Content.Client/UserInterface/Systems/Chat/Controls/ChannelFilterPopup.xaml
> +    xmlns:gfx="clr-namespace:Robust.Client.Graphics;assembly=Robust.Client"
закрывай изменения тэгами корвакса

2024-10-30 18:39 UTC, AwareFoxy commented on Content.Client/UserInterface/Systems/Chat/Controls/ChannelFilterPopup.xaml.cs
> +using Content.Shared.CCVar;
в Corvax CVars, закрывай изменения в файле тэгами

2024-10-30 18:39 UTC, AwareFoxy commented on Content.Client/UserInterface/Systems/Chat/Widgets/ChatBox.xaml.cs
> +using Content.Shared.CCVar;
тоже самое, Corvax CVars, изменения с тэгами

2024-10-30 18:39 UTC, AwareFoxy commented on Content.Shared/CCVar/CCVars.cs
> +        /// <summary>
Corvax CVa- думаю ты понял.

2024-10-30 18:39 UTC, AwareFoxy commented on Resources/Locale/ru-RU/chat/highlights.ftl
> +highlights-head-of-security = Глава Службы Безопасности, "ГСБ", Безопасность, "Охрана", Командование
```suggestion
highlights-head-of-security = Глава Службы Безопасности, "ГСБ", Безопасности, "СБ", Командование
```

2024-10-30 20:43 UTC, AwareFoxy commented
За исключением мелочей выше код выглядит нормально

2024-11-01 12:41 UTC, AwareFoxy approved these changes

2024-11-02 07:52 UTC, Tornado-Technology commented
Это сейчас имеет смысл? Данный PR ещё открыт у визардов, смысл заниматся ранним мерджем, до закрытия и окончательного ревью?

2024-11-09 02:38 UTC, merged

2024-11-12 06:30 UTC, Snorkcom commented
на будущее улучшение: можно добавить возможность проигрывать звук (при галочке) и выбор цвета выделения

2024-11-12 07:49 UTC, TokenStyle commented
> Это сейчас имеет смысл? Данный PR ещё открыт у визардов, смысл заниматся ранним мерджем, до закрытия и окончательного ревью?

Я когда брал он не был в обсуждении у мейнтейнеров. Они очень быстро за ПР взялись