Предатели более 10 разновидностей [ONLY ROLE PLAY]
space-syndicate/space-station-14-next pull request #17
Opened 2024-10-31 16:40 UTC by TokenStyle

## Описание PR
Добавляет более 10 "боссов" которые добавляют дополнительное РП описание для предателей. Кроме дополнительного лорного текста в меню персонажа, описания в чате **ничего** не меняет. Никаких "скидок" или "game changing" механик.
Взято с [Traitor flavor (take 3)](https://github.com/space-wizards/space-station-14/pull/30198)

## Почему / Баланс
Потому-что РП всегда хорошо.

## Технические детали
Изменил только `Content.Server/GameTicking/Rules/TraitorRuleSystem.cs` и `Content.Server/Objectives/ObjectivesSystem.cs` для отображения "боссов" в чате игры, меню персонажа. В конце игры поправил отображение антагонистов, чтобы показывались по "группам", в зависимости от "ключевых слов синдиката".

## Медиа

## Требования

https://github.com/user-attachments/assets/8d012dd2-1e3d-4956-9367-98ee6a9fba0f

- [x] Я прочитал(а) и следую [Рекомендациям по оформлению Pull Request и Changelog](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] Я добавил(а) медиафайлы к этому PR или он не требует демонстрации в игре.

## Критические изменения

**Список изменений**

:cl:
- add: Наниматели из Синдиката теперь выдают задания при получении роли Предателя в начале раунда, или "Спящего предателя" в середине раунда. У одного предателя может быть только один босс.
- add: Синдикат теперь имеет более 10 фракций.

2024-10-31 16:51 UTC, lzk228 commented
добавляет стену текста в чат, которую никто не будет читать, ура

2024-10-31 18:45 UTC, tripsov commented
Небольшое, но очень приятное дополнение, дающее простор для отыгрыша

2024-11-02 16:16 UTC, Vonsant commented
@TokenStyle пофикси конфликты.

2024-11-03 03:01 UTC, AwareFoxy requested changes
Пожалуйста закрой всё // Corvax-Next-nazvanie-izmenenie

Просто представь насколько это будет потом не оч мерджить :pray:

2024-11-08 02:19 UTC, AwareFoxy requested changes

2024-11-08 02:19 UTC, AwareFoxy commented on Content.Server/GameTicking/Rules/Components/TraitorRuleComponent.cs
> +    public ProtoId<DatasetPrototype> ObjectiveIssuers = "TraitorFlavor";
```suggestion
    public ProtoId<DatasetPrototype> ObjectiveIssuers = "TraitorFlavor"; // Corvax-Next-Traitors
```

2024-11-08 02:19 UTC, AwareFoxy commented on Content.Server/GameTicking/Rules/Components/TraitorRuleComponent.cs
> +    public string ObjectiveIssuer = string.Empty;
```suggestion
    public string ObjectiveIssuer = string.Empty; // Corvax-Next-Traitors
```

2024-11-08 02:19 UTC, AwareFoxy commented on Content.Server/GameTicking/Rules/TraitorRuleSystem.cs
> +        SubscribeLocalEvent<TraitorRuleComponent, ObjectivesTextGetInfoEvent>(OnObjectivesTextGetInfo, after: new[] { typeof(AntagSelectionSystem) });
```suggestion
        SubscribeLocalEvent<TraitorRuleComponent, ObjectivesTextGetInfoEvent>(OnObjectivesTextGetInfo, after: new[] { typeof(AntagSelectionSystem) }); // Corvax-Next-Traitors
```

2024-11-08 02:19 UTC, AwareFoxy commented on Content.Server/GameTicking/Rules/TraitorRuleSystem.cs
> +        component.ObjectiveIssuer = issuer;
```suggestion
        component.ObjectiveIssuer = issuer; // Corvax-Next-Traitors
```

2024-11-08 02:19 UTC, AwareFoxy commented on Content.Server/GameTicking/Rules/TraitorRuleSystem.cs
> +        _antag.SendBriefing(traitor, GenerateBriefing(component.Codewords, code, issuer), Color.Crimson, component.GreetSoundNotification);
```suggestion
        _antag.SendBriefing(traitor, GenerateBriefing(component.Codewords, code, issuer), Color.Crimson, component.GreetSoundNotification); // Corvax-Next-Traitors
```

2024-11-08 02:19 UTC, AwareFoxy commented on Content.Server/GameTicking/Rules/TraitorRuleSystem.cs
> +            Briefing = GenerateBriefingCharacter(component.Codewords, code, issuer)
```suggestion
            Briefing = GenerateBriefingCharacter(component.Codewords, code, issuer) // Corvax-Next-Traitors
```

2024-11-08 02:19 UTC, AwareFoxy commented on Content.Server/GameTicking/Rules/TraitorRuleSystem.cs
> +    private void OnObjectivesTextGetInfo(EntityUid uid, TraitorRuleComponent comp, ref ObjectivesTextGetInfoEvent args)
```suggestion
// Corvax-Next-Traitors-Start
    private void OnObjectivesTextGetInfo(EntityUid uid, TraitorRuleComponent comp, ref ObjectivesTextGetInfoEvent args)
```

2024-11-08 02:19 UTC, AwareFoxy commented on Content.Server/GameTicking/Rules/TraitorRuleSystem.cs
> +
```suggestion
// Corvax-Next-Traitors-End

```

2024-11-08 02:19 UTC, AwareFoxy commented on Content.Server/GameTicking/Rules/TraitorRuleSystem.cs
> +    private string GenerateBriefing(string[] codewords, Note[]? uplinkCode, string objectiveIssuer)
```suggestion
// Corvax-Next-Traitors-Start
    private string GenerateBriefing(string[] codewords, Note[]? uplinkCode, string objectiveIssuer)
```

2024-11-08 02:19 UTC, AwareFoxy commented on Content.Server/GameTicking/Rules/TraitorRuleSystem.cs
> +        sb.AppendLine("\n" + Loc.GetString($"traitor-role-clarity"));
```suggestion
        sb.AppendLine("\n" + Loc.GetString($"traitor-role-clarity"));
        // Corvax-Next-Traitors-End
```

2024-11-08 02:19 UTC, AwareFoxy commented on Content.Server/Objectives/ObjectivesSystem.cs
> +        var summaries = new Dictionary<string, Dictionary<string, Dictionary<string, List<(EntityUid, string)>>>>();
```suggestion
        var summaries = new Dictionary<string, Dictionary<string, Dictionary<string, List<(EntityUid, string)>>>>(); // Corvax-Next-Traitors

```

2024-11-08 02:19 UTC, AwareFoxy commented on Content.Server/Objectives/ObjectivesSystem.cs
> +            // first group the gamerules by their factions, for example 2 different dragons
```suggestion
            // first group the gamerules by their factions, for example 2 different dragons
            // Corvax-Next-Traitors-Start
```

2024-11-08 02:19 UTC, AwareFoxy commented on Content.Server/Objectives/ObjectivesSystem.cs
> +            }
```suggestion
            }
            // Corvax-Next-Traitors-End

```

2024-11-08 02:19 UTC, AwareFoxy commented on Content.Server/Objectives/ObjectivesSystem.cs
> +    public string GetTitle(Entity<MindComponent?> mind, string name = "")
```suggestion
    public string GetTitle(Entity<MindComponent?> mind, string name = "") // Corvax-Next-Traitors

```

2024-11-08 02:19 UTC, AwareFoxy commented on Content.Server/Objectives/ObjectivesSystem.cs
> +public record struct ObjectivesTextGetInfoEvent(List<(EntityUid, string)> Minds, string AgentName, string? Faction = null);
```suggestion
public record struct ObjectivesTextGetInfoEvent(List<(EntityUid, string)> Minds, string AgentName, string? Faction = null); // Corvax-Next-Traitors
```

2024-11-08 02:19 UTC, AwareFoxy commented on Resources/Locale/en-US/game-ticking/game-presets/preset-traitor.ftl
> +traitor-role-moreinfo =
Вынести в одну большую отдельную локаль(сделай ещё там папку _corvaxnext сразу)

2024-11-08 02:19 UTC, AwareFoxy commented on Resources/Locale/en-US/traitor/flavor.ftl
> +traitor-arc-intro = You are the ARC terrorist.
в папку _CorvaxNext

2024-11-08 02:19 UTC, AwareFoxy commented on Resources/Locale/ru-RU/game-ticking/game-presets/preset-traitor.ftl
> +
Вынести в одну большую отдельную локаль

2024-11-08 02:19 UTC, AwareFoxy commented on Resources/Locale/ru-RU/traitor/flavor.ftl
> +traitor-arc-intro = Ты активист консилиума по борьбе за права животных - "ARC"
Вынести в одну большую отдельную локаль, в папку _CorvaxNext

2024-11-08 02:19 UTC, AwareFoxy commented on Resources/Prototypes/Roles/Antags/traitor.yml
> +  name: roles-antag-traitor-name
Есть ли в этом смысл?

2024-11-10 09:41 UTC, Tornado-Technology commented
Жду разрешение конфликтов и правок фокса

2024-12-03 20:40 UTC, Vonsant commented
@TokenStyle ты будешь допиливать?

2025-05-18 04:31 UTC, JerryImMouse commented
> @TokenStyle ты будешь допиливать?

не будет

2025-05-18 04:31 UTC, closed without merging