Fatherless Turrets
space-syndicate/space-station-14-next pull request #173
Opened 2024-12-19 16:00 UTC by CaptainMaru

## Описание PR
Добавлена новая фракция "без фракции" которая враждебна ко всем существующим фракциям ИИ.
Добавлена турель без фракции.

## Требования
- [X] Я прочитал(а) и следую [Рекомендациям по оформлению Pull Request и Changelog]
- [X] Я добавил(а) медиафайлы к этому PR или он не требует демонстрации в игре.

**Список изменений**
:cl: RatIRL
- add: Новая фракция для искусственного интеллекта мобов
- add: Добавлены турели без фракции. Они агрессивны ко всему живому, не исключая агрессивную фауну.

2024-12-19 16:57 UTC, FireNameFN requested changes
Надо всё в папки `_CorvaxNext` положить.

2024-12-20 09:40 UTC, CaptainMaru commented
Короче, залил офам. Закрываю

2024-12-20 09:40 UTC, closed without merging

2024-12-20 10:03 UTC, Vonsant commented
> Короче, залил офам. Закрываю

Им тоже залил неправильно.

2024-12-20 19:54 UTC, CaptainMaru commented
> > Короче, залил офам. Закрываю
> 
> Им тоже залил неправильно.

💀