Снежки
space-syndicate/space-station-14-next pull request #179
Opened 2024-12-21 20:07 UTC by CaptainSqrBeard

## Описание PR
Добавлены снежки. Их можно метать в людей и наносить урон по стамине.

Добавлен снежколеп, создающий снежки при клике на тайл снега. Его можно напечатать на автолате.

## Почему / Баланс
Просто предмет для веселья на манер боксёрских перчаток.

## Ссылка на ветку
Предложка: https://discord.com/channels/919301044784226385/1309045735894941788
(хотя предложка тут скорее просто источник некоторого вдохновения)

Ветка: https://discord.com/channels/919301044784226385/1319812837924667392

## Технические детали
`Destructible.Thresholds.Behaviors.SpillBehavior` получил новое поле, дающее приглушить звук от выплёскивания реагентов.

Новый компонент `FromTileCrafterComponent` и система `FromTileCrafterSystem` для спавна при помощи объекта с этим компонентом по клику на определённые тайлы.

## Медиа
https://github.com/user-attachments/assets/e66d09ec-384c-495a-9720-a9d770226f85

## Критические изменения

**Список изменений**
:cl: csqrb
- add: Добавлены снежки! Для их получения используйте снежколеп из автолата.

2024-12-21 21:37 UTC, FireNameFN commented on Content.Shared/_CorvaxNext/FromTileCrafter/Components/FromTileCrafterComponent.cs
> +    }
Самый неглубокий Clone()

2024-12-21 21:37 UTC, FireNameFN commented on Content.Shared/_CorvaxNext/FromTileCrafter/Components/FromTileCrafterComponent.cs
> +    }
primery constructor

2024-12-21 21:38 UTC, FireNameFN commented on Content.Shared/_CorvaxNext/FromTileCrafter/Systems/FromTileCrafterSystem.cs
> +        base.Initialize();
Лишнее

2024-12-21 21:42 UTC, FireNameFN commented on Content.Shared/_CorvaxNext/FromTileCrafter/Systems/FromTileCrafterSystem.cs
> +            _robustRandom.NextFloat() - 0.5f * spread);
```suggestion
        var spread = mapGrid.TileSize * 0.05f;
        var offset = new Vector2(
            _robustRandom.NextFloat() - spread,
            _robustRandom.NextFloat() - spread);
```

2024-12-21 21:44 UTC, FireNameFN commented on Content.Shared/_CorvaxNext/FromTileCrafter/Systems/FromTileCrafterSystem.cs
> +        var spread = mapGrid.TileSize * 0.1f;
```suggestion
        var tileRef = _maps.GetTileRef(gridUid, grid, args.GridTile);
        var coords = _maps.ToCoordinates(tileRef, grid);

        var spread = grid.TileSize * 0.1f;
```

2024-12-21 22:45 UTC, CaptainSqrBeard commented on Content.Shared/_CorvaxNext/FromTileCrafter/Components/FromTileCrafterComponent.cs
> +    }
сам приверяй

2024-12-21 22:57 UTC, FireNameFN commented on Content.Shared/_CorvaxNext/FromTileCrafter/Components/FromTileCrafterComponent.cs
> +    }
Ну primary, блин

2024-12-22 00:18 UTC, FireNameFN requested changes

2024-12-22 00:18 UTC, FireNameFN commented on Content.Shared/_CorvaxNext/FromTileCrafter/Systems/FromTileCrafterSystem.cs
> +    }
```suggestion
    private void OnFromTileCraftComplete(Entity<FromTileCrafterComponent> ent, ref FromTileCraftDoAfterEvent args)
    {
        if (_netManager.IsClient)
            return;
    
        var comp = ent.Comp;
        if (args.Handled || args.Cancelled)
            return;

        var gridUid = GetEntity(args.Grid);
        if (!TryComp<MapGridComponent>(gridUid, out var grid))
            return;

        var tileRef = _maps.GetTileRef(gridUid, grid, args.GridTile);
        var coords = _maps.ToCoordinates(tileRef, grid);

        var spread = comp.Spread * grid.TileSize;
        var offset = new Vector2(
            (_robustRandom.NextFloat() - 0.5f) * spread + grid.TileSize * 0.5f,
            (_robustRandom.NextFloat() - 0.5f) * spread + grid.TileSize * 0.5f);

        Spawn(ent.Comp.EntityToSpawn, coords.Offset(offset));
    }
```

2024-12-22 00:18 UTC, FireNameFN commented on Content.Shared/_CorvaxNext/FromTileCrafter/Systems/FromTileCrafterSystem.cs
> +            (_robustRandom.NextFloat() - 0.5f) * spread + grid.TileSize * 0.5f);
```suggestion
        var spread = comp.Spread * grid.TileSize;
        var offset = new Vector2(
            ((_robustRandom.NextFloat() - 0.5f) * comp.Spread + 0.5f) * grid.TileSize,
            ((_robustRandom.NextFloat() - 0.5f) * comp.Spread + 0.5f) * grid.TileSize);
```

2024-12-22 00:20 UTC, CaptainSqrBeard commented on Content.Shared/_CorvaxNext/FromTileCrafter/Components/FromTileCrafterComponent.cs
> +    }
я попробовал сделать это и у меня перестала билдится игра, хз

2024-12-22 00:21 UTC, CaptainSqrBeard commented on Content.Shared/_CorvaxNext/FromTileCrafter/Components/FromTileCrafterComponent.cs
> +    }
чо

2024-12-22 12:11 UTC, CaptainSqrBeard commented on Content.Shared/_CorvaxNext/FromTileCrafter/Components/FromTileCrafterComponent.cs
> +    }
так и не разобрался в чём проблема

2024-12-24 00:44 UTC, FireNameFN approved these changes

2024-12-24 00:46 UTC, merged