ЭТО ЖЕ ТАРХУН!!!
space-syndicate/space-station-14-next pull request #18
Opened 2024-11-03 09:36 UTC by loksill

## Описание PR

## Почему / Баланс

Добавлен новый напиток - ТАРХУН!!!
## Технические детали

## Медиа

## Требования

- [X] Я прочитал(а) и следую [Рекомендациям по оформлению Pull Request и Changelog](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] Я добавил(а) медиафайлы к этому PR или он не требует демонстрации в игре.

## Критические изменения

**Список изменений**

2024-11-03 16:34 UTC, p0etus commented on Resources/Prototypes/Corvax/Reagents/Consumable/Drink/soda.yml
> +  color: "#99bb43"
> тархуну бы цвет на более зеленый поменять, очень похож на рвоту

Он и на вкус примерной такой, фича.

2024-11-03 22:36 UTC, AwareFoxy requested changes

2024-11-03 22:36 UTC, AwareFoxy commented on Resources/Prototypes/Corvax/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
>    - type: Sealable
Убери это, обычно простого переоткрытия файла хватает
![image](https://github.com/user-attachments/assets/37e6a4a1-84be-42f2-a78e-e12d0f18ea7b)

2024-11-03 22:36 UTC, AwareFoxy commented on Resources/Prototypes/Corvax/Reagents/Consumable/Drink/soda.yml
> +        type: Remove
Тоже самое что и выше

2024-11-03 22:49 UTC, lzk228 commented on Resources/Prototypes/Corvax/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
>    - type: Sealable
смотря где, в редакторе это может быть не настроено

2024-11-04 08:18 UTC, loksill commented on Resources/Prototypes/Corvax/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
>    - type: Sealable
А на что это влияет?

2024-11-07 16:58 UTC, NotSoDana requested changes

2024-11-07 16:58 UTC, NotSoDana commented on Resources/Prototypes/Corvax/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
Бред планетарного масштаба.
1) Нахуя напиток нужен если это тупо кола с другим цветом, вы даже спрайт для него поленились сделать, не говоря уже о содержимом стакана
2) Названия пишутся с маленькой буквы и в ФТЛах А НЕ В ПРОТОТИПЕ

Либо делайте качественно, либо не делайте вообще

2024-11-07 17:01 UTC, NotSoDana commented on Resources/Prototypes/Corvax/Reagents/Consumable/Drink/soda.yml
Вы чё серьёзно сделали линк описания и названия реагента на фтл, но не сделали сам фтл?
![image](https://github.com/user-attachments/assets/0387c02c-dea9-4d48-9a45-cfbf327a57c7)

2024-11-10 08:14 UTC, AwareFoxy commented
Идея классная, реализация нет.

Разработчики Corvax Next:tm: переделают ваш ПР в будущем.

2024-11-10 08:14 UTC, closed without merging