Раундстартовые газы
space-syndicate/space-station-14-next pull request #184
Opened 2024-12-23 23:19 UTC by Vonsant

## Описание PR

Добавлены газовый насос, объемный газовый насос и газовый смеситель, которые могут быть замаплены включенными и останутся таковыми при запуске карты. Требуются для маппинга, не для станций.

## Почему / Баланс

Запрос от мапперов.

## Технические детали

В каждый трубный файл добавлено по чутка.

**Список изменений**

:cl:
- add: Добавлены всякие газосмесители запущенные раундстартом.

2024-12-23 23:40 UTC, FireNameFN requested changes
Не уверен, что нужна вся эта работа с UI. Попробуй убрать.

2024-12-23 23:40 UTC, FireNameFN commented on Content.Server/Atmos/Piping/Binary/EntitySystems/GasVolumePumpSystem.cs
> +			SubscribeLocalEvent<GasVolumePumpComponent, MapInitEvent>(OnMapInit); // Corvax-Next-AutoPipe
```suggestion
			SubscribeLocalEvent<GasVolumePumpComponent, MapInitEvent>(OnMapInit); // Corvax-Next-AutoPipes
```

2024-12-23 23:40 UTC, FireNameFN commented on Content.Server/Atmos/Piping/Binary/EntitySystems/GasPressurePumpSystem.cs
> +                _userInterfaceSystem.CloseUi(uid, GasPressurePumpUiKey.Key);
```suggestion
```

2024-12-23 23:40 UTC, FireNameFN commented on Content.Server/Atmos/Piping/Binary/EntitySystems/GasVolumePumpSystem.cs
> +                _userInterfaceSystem.CloseUi(uid, GasVolumePumpUiKey.Key);
```suggestion
```

2024-12-23 23:40 UTC, FireNameFN commented on Content.Server/Atmos/Piping/Trinary/EntitySystems/GasMixerSystem.cs
> +                _userInterfaceSystem.CloseUi(uid, GasFilterUiKey.Key);
```suggestion
                UpdateAppearance(uid, mixer);
```

2024-12-23 23:45 UTC, FireNameFN approved these changes
Нафиг не понимаю, как этот код работает.

2024-12-23 23:51 UTC, Vonsant commented
> Нафиг не понимаю, как этот код работает.

Забей, это атмосия, там ногу сломит сам сатана.

2024-12-23 23:59 UTC, merged

2024-12-24 03:29 UTC, CaptainSqrBeard commented
а выставление в прототипе `enabled: true` не работает?

2024-12-24 13:57 UTC, Vonsant commented
> а выставление в прототипе `enabled: true` не работает?

Нет

2024-12-24 16:19 UTC, CaptainSqrBeard commented
> > а выставление в прототипе `enabled: true` не работает?
> 
> Нет

а что там происходит?