Move discipline lock from T3 to T4
space-syndicate/space-station-14-next pull request #19
Opened 2024-11-04 01:30 UTC by TasiWeynad

## Описание PR
Изменил цифру блокировки изучения технологий на Т4

## Почему / Баланс
Даст больше мотиваций для исследований технологий в RnD, больше возможностей для игры.

Баланс: Считаю, что влияние будет минимальным, так как при текущих реалиях онлайна и экипажа не всегда исследуется даже четверть или пятая часть всех технологий.

Ссылка на предложение в дискорд сервере: https://discord.com/channels/919301044784226385/1301821257695887411

## Технические детали
Изменение одной циферки по пути Content.Shared/Research/Prototypes/TechDisciplinePrototype.cs

## Медиа
![20241104081436_1](https://github.com/user-attachments/assets/d51d15ca-afc2-410c-b9a3-1a1fc5cdda08)

## Требования
- [X] Я прочитал(а) и следую [Рекомендациям по оформлению Pull Request и Changelog](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] Я добавил(а) медиафайлы к этому PR или он не требует демонстрации в игре.

**Список изменений**
:cl:
- tweak: Теперь можно исследовать Т3 технологии всех

2024-11-07 02:25 UTC, AwareFoxy requested changes
Меняй это в прототипе, не в коде.

2024-11-08 16:56 UTC, TasiWeynad commented
> Меняй это в прототипе, не в коде.

Сделано.

2024-11-09 01:53 UTC, FireNameFN commented
@AwareFoxy Всё таки разрешишь сделать так, как я хочу?

2024-11-09 02:11 UTC, FireNameFN commented
Пометку `# Corvax-Next-TechLock` добавьте.

2024-11-09 02:15 UTC, AwareFoxy requested changes

2024-11-09 02:15 UTC, AwareFoxy commented on Resources/Prototypes/Research/disciplines.yml
> +  lockoutTier: 4
```suggestion
  lockoutTier: 4 # Corvax-Next-TechLock
```

2024-11-09 02:15 UTC, AwareFoxy commented on Resources/Prototypes/Research/disciplines.yml
> +  lockoutTier: 4
```suggestion
  lockoutTier: 4 # Corvax-Next-TechLock
```

2024-11-09 02:15 UTC, AwareFoxy commented on Resources/Prototypes/Research/disciplines.yml
> +  lockoutTier: 4
```suggestion
  lockoutTier: 4 # Corvax-Next-TechLock
```

2024-11-09 02:15 UTC, AwareFoxy commented on Resources/Prototypes/Research/disciplines.yml
> +  lockoutTier: 4
```suggestion
  lockoutTier: 4 # Corvax-Next-TechLock
```

2024-11-09 02:16 UTC, AwareFoxy approved these changes

2024-11-09 02:29 UTC, merged