Resomi(Update)
space-syndicate/space-station-14-next pull request #191
Opened 2024-12-25 10:03 UTC by pofitlo-Git

## Описание PR

Добавление новой способности, фич и фикс багов

Способность "прислушаться", позволяет слышать существ за стенами в радиусе 8 тайлов, пока персонаж стоит. движение прерывает способность. 

## Почему / Баланс

Все-ещё привожу к тому, какими они должны были быть по диздоку

## Медиа

-not yet

**Список изменений**

- [x] Добавлена новая способность, позволяющая слышать существ за стенами
- [ ] Исправлен баг с вечным *задыхается* у резоми
- [ ] Добавлен уникальный звук голоса
- [ ] Добавлена фича с тем, что они проще таскаются, но сами, наоборот, таскают хуже
- [ ] Они хуже усваивают злаки
- [ ] Исправлены некоторые дисплейсмент карты 
- [ ] Исправлен баг с тем, что у них нельзя было отключить акцент
- [ ] Убрана возможность им спавниться за ОБР, ниндзю и ЯО
- [ ] Исправлен баг с тем, что способность переключения ловкости иногда не переключала иконку
- [ ] Добавлена английская локализация

2024-12-31 19:33 UTC, pofitlo-Git commented
на всякий случай: пока не мерджите

2025-01-01 07:14 UTC, pofitlo-Git commented
ладно..... теперь можно ^_^

2025-01-01 07:26 UTC, FireNameFN requested changes

2025-01-01 07:26 UTC, FireNameFN commented on Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
> +  - Resomi
```suggestion
  - Resomi # Corvax-Next-Resomi
```

2025-01-01 07:26 UTC, FireNameFN commented on Resources/Prototypes/Traits/speech.yml
> +    - type: ResomiAccent #Corvax-Next-Resomi
```suggestion
    - type: ResomiAccent # Corvax-Next-Resomi
```

2025-01-01 07:26 UTC, FireNameFN commented on Resources/Locale/ru-RU/_corvaxNext/abilitties/listen-up.ftl
АААААААААААААААААААААААААААААААААААААААААААА

2025-01-01 07:26 UTC, FireNameFN commented on Content.Client/_CorvaxNext/Overlays/ListenUpSystem.cs
> +        return _listenUpOverlay = new ListenUpOverlay(radius, sprite);
```suggestion
        return _listenUpOverlay = new(radius, sprite);
```

2025-01-01 07:26 UTC, FireNameFN commented on Content.Client/_CorvaxNext/Overlays/ListenUpSystem.cs
> +        return _listenUpOverlay = new ListenUpOverlay(radius, sprite);
Обычно это считают некрасивым и пушит в две строчки.

2025-01-01 07:26 UTC, FireNameFN commented on Content.Client/_CorvaxNext/Overlays/ListenUpSystem.cs
> +        if (_player.LocalEntity == null)
```suggestion
        if (_player.LocalEntity is null)
```

2025-01-01 07:26 UTC, FireNameFN commented on Content.Server/_CorvaxNext/Resomi/Abilities/ListenUpSkillSystem.cs
> +
```suggestion
```

2025-01-01 07:26 UTC, FireNameFN commented on Content.Server/_CorvaxNext/Resomi/Abilities/ListenUpSystem.cs
> +        base.Initialize();
```suggestion
```

2025-01-01 07:26 UTC, FireNameFN commented on Content.Shared/_CorvaxNext/Resomi/Abilities/Hearing/ListenUpComponent.cs
> +    public SpriteSpecifier.Rsi Sprite = new SpriteSpecifier.Rsi(new("/Textures/_CorvaxNext/Mobs/Species/Resomi/Abilities/noise_effect.rsi"), "noise");
```suggestion
    public SpriteSpecifier Sprite = new SpriteSpecifier.Rsi(new("/Textures/_CorvaxNext/Mobs/Species/Resomi/Abilities/noise_effect.rsi"), "noise");
```
Для большей совместимости, если я правильно понимаю.

2025-01-01 07:26 UTC, FireNameFN commented on Resources/Prototypes/Entities/Structures/Specific/Anomaly/anomaly_injectors.yml
> +          Resomi: #Corvax-Next-Resomi
```suggestion
          Resomi: # Corvax-Next-Resomi
```

2025-01-01 07:26 UTC, FireNameFN commented on Resources/Prototypes/Entities/Structures/Specific/Anomaly/anomaly_injectors.yml
> +          Resomi: #Corvax-Next-Resomi
```suggestion
          Resomi: # Corvax-Next-Resomi
```

2025-01-01 07:26 UTC, FireNameFN commented on Resources/Prototypes/Entities/Structures/Specific/Anomaly/anomaly_injectors.yml
> +          Resomi: #Corvax-Next-Resomi
```suggestion
          Resomi: # Corvax-Next-Resomi
```

2025-01-01 07:26 UTC, FireNameFN commented on Resources/Prototypes/Entities/Structures/Specific/Anomaly/anomaly_injectors.yml
> +          Resomi: #Corvax-Next-Resomi
```suggestion
          Resomi: # Corvax-Next-Resomi
```

2025-01-01 07:26 UTC, FireNameFN commented on Resources/Prototypes/Entities/Structures/Specific/Anomaly/anomaly_injectors.yml
> +          Resomi: #Corvax-Next-Resomi
```suggestion
          Resomi: # Corvax-Next-Resomi
```

2025-01-01 07:26 UTC, FireNameFN commented on Resources/Prototypes/Entities/Structures/Specific/Anomaly/anomaly_injectors.yml
> +          Resomi: #Corvax-Next-Resomi
```suggestion
          Resomi: # Corvax-Next-Resomi
```

2025-01-01 07:26 UTC, FireNameFN commented on Resources/Prototypes/Entities/Structures/Specific/Anomaly/anomaly_injectors.yml
> +          Resomi: #Corvax-Next-Resomi
```suggestion
          Resomi: # Corvax-Next-Resomi
```

2025-01-01 07:26 UTC, FireNameFN commented on Resources/Prototypes/Entities/Structures/Specific/Anomaly/anomaly_injectors.yml
> +          Resomi: #Corvax-Next-Resomi
```suggestion
          Resomi: # Corvax-Next-Resomi
```

2025-01-01 07:26 UTC, FireNameFN commented on Resources/Prototypes/Entities/Structures/Specific/Anomaly/anomaly_injectors.yml
> +          Resomi: #Corvax-Next-Resomi
```suggestion
          Resomi: # Corvax-Next-Resomi
```

2025-01-01 07:26 UTC, FireNameFN commented on Resources/Prototypes/Entities/Structures/Specific/Anomaly/anomaly_injectors.yml
> +          Resomi: #Corvax-Next-Resomi
```suggestion
          Resomi: # Corvax-Next-Resomi
```

2025-01-01 07:26 UTC, FireNameFN commented on Resources/Textures/_CorvaxNext/Mobs/Species/Resomi/Abilities/ListenUp/meta.json
> +  "license": "CC-BY-SA-3.0",
Кмин говорит другую лицензию использовать.

2025-01-01 07:26 UTC, FireNameFN commented on Resources/Textures/_CorvaxNext/Structures/Specific/Anomalies/inner_anom_layer.rsi/meta.json
> +  "license": "CC-BY-SA-3.0",
И тут.

2025-01-01 14:13 UTC, Vonsant commented on Resources/Textures/_CorvaxNext/Mobs/Species/Resomi/Abilities/ListenUp/meta.json
> +  "license": "CC-BY-SA-3.0",
А? Да любую открытую, хоть CC-BY-SA-3.0, хоть CC-BY-SA-4.0. Я просто говорила, что нужна открытая лицензия.

https://creativecommons.org/licenses/by-sa/4.0/deed.ru

2025-01-01 14:13 UTC, Vonsant commented on Resources/Textures/_CorvaxNext/Mobs/Species/Resomi/Abilities/ListenUp/meta.json
> +  "license": "CC-BY-SA-3.0",
Всё ок, 3 тож подходит.

2025-01-01 14:34 UTC, pofitlo-Git commented on Content.Client/_CorvaxNext/Overlays/ListenUpSystem.cs
> +        return _listenUpOverlay = new ListenUpOverlay(radius, sprite);
скажи плиз конкретно что ты от меня хочешь

2025-01-01 14:47 UTC, pofitlo-Git commented on Content.Client/_CorvaxNext/Overlays/ListenUpSystem.cs
> +        if (_player.LocalEntity == null)
![image](https://github.com/user-attachments/assets/7a0e6c2b-8173-4fd1-bacb-11fec66900db)
VS
![image](https://github.com/user-attachments/assets/140d3869-a26e-486d-874e-b58b4839d896)

2025-01-01 14:47 UTC, FireNameFN commented on Content.Client/_CorvaxNext/Overlays/ListenUpSystem.cs
> +        return _listenUpOverlay = new ListenUpOverlay(radius, sprite);
```
_listenUpOverlay = new(radius, sprite);

return _listenUpOverlay;
```

2025-01-01 16:48 UTC, Vonsant commented
И щас все такие кто требовал удолить Резоми возбудятся в едином порыве
![image](https://github.com/user-attachments/assets/8359c093-c0bb-426b-8a6f-233f13ac4551)

2025-01-01 16:52 UTC, pofitlo-Git commented
> И щас все такие кто требовал удолить Резоми возбудятся в едином порыве ![image](https://private-user-images.githubusercontent.com/118206719/399576389-8359c093-c0bb-426b-8a6f-233f13ac4551.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3NTA1NTMsIm5iZiI6MTczNTc1MDI1MywicGF0aCI6Ii8xMTgyMDY3MTkvMzk5NTc2Mzg5LTgzNTljMDkzLWMwYmItNDI2Yi04YTZmLTIzM2YxM2FjNDU1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMVQxNjUwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzEwMzA1NjkwMjk3NDE0MWZlN2E4NzkzN2JkNjUyNWVlODg1YTQzMmYyNmIxOWIzNTU0ODU2NTk3ZGUxOTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uzDho-ELfejWxpxsqP8ESmXn1A_w-39GHl96tidHhoI)

)))

2025-01-03 09:07 UTC, Vonsant submitted a review, later dismissed

2025-01-03 13:38 UTC, merged

2025-01-03 15:39 UTC, pofitlo-Git commented
ждем предложек откатить ПР из за того, что резоми стали слишком имбалансные с новой способностью

2025-01-04 17:02 UTC, Hemomancer commented
> ждем предложек откатить ПР из за того, что резоми стали слишком имбалансные с новой способностью

Жду отката ПРа из-за выбивающихся иконок способностей....