Resomi
space-syndicate/space-station-14-next pull request #27
Opened 2024-11-08 12:02 UTC by pofitlo-Git

## Описание PR

Добавление новой расы - Резоми

## Технические детали

Имеют примерно следующие функции
- Они имеют лишь 70% от обычного здоровья
- у них есть переключаемая способность, которая позволяет им перепрыгивать через столы и незначительно ускоряться, но взамен тратит значительное количество выносливости
- другие расы могут брать их на руки и имеют возможность засовывать их в сумки, при условии, что слот рюкзака на резоми пустует... возможно... попытка засунуть их в БС сумку... приведет к плачевным исходам
- Вспышки действуют на них в 2 рааа дольше из за чувствительных глаз
- Они не могут использовать крупнокалиберное оружие, в виду того, что у них всегда будет высокий разброс с ним
- Они имеют способность "прислушаться" что требует много времени для подготовки, но позволяет слышать другие организмы за стенами
- У них есть ночное зрение на 1-3 тайла
## Медиа
 
чуть позже

## Требования

- [X] Я прочитал(а) и следую [Рекомендациям по оформлению Pull Request и Changelog](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] Я добавил(а) медиафайлы к этому PR или он не требует демонстрации в игре.

## Критические изменения

Добавление к FlashSystem модификатора для продления действия вспышки

**Список изменений**

##ToDo
- [X] Переместить мой ПР с репозитория [оффов](https://github.com/space-wizards/space-station-14/pull/30202)
- [ ] полностью Закончить с локализацией 
- [ ] Добавить дисплейсмент карты для одежды
- [ ] Добавить способность для переключения "ловкости"
- [ ] Добавить возможность брать их на руки
- [ ] Добавить запрет на использование КК оружия
- [ ] Добавить ночное зрение
- [ ] Добавить возможность слышать через стены

:cl:
- add: добавлена новая игровая раса - Резоми!

2024-11-08 17:14 UTC, kosticia commented
Здоровье не меняй, молю. На серверах где есть сранные фелиниды их лечат по полтора часа так как на автомате бьют дефибом когда у них 200 урона

2024-11-09 00:57 UTC, FireNameFN requested changes

2024-11-09 00:57 UTC, FireNameFN commented on Content.Server/_CorvaxNext/Resomi/Abilities/ResomiSkillSystem.cs
> +namespace Content.Server.Resomi.Abilities
Неймспейс Некста нужен. И сделай его не через фигурные скобки.

2024-11-09 00:57 UTC, FireNameFN commented on Content.Server/_CorvaxNext/Resomi/Abilities/ResomiSkillComponent.cs
> +namespace Content.Server.Resomi.Abilities
То же самое.

2024-11-10 08:10 UTC, PuroSlavKing commented
KFC UPDATE, легенда 🙏

2024-11-10 09:46 UTC, Tornado-Technology commented
No way. кажись надо будит шутить про open blance PR

2024-11-10 15:00 UTC, AwareFoxy commented
> No way. кажись надо будит шутить про open blance PR

про диздок PR :trollface:

2024-11-19 11:46 UTC, pofitlo-Git commented
@Tornado-Technology 
@AwareFoxy 

Прошу ревью кода и прототипов. На баги я открою его, когда доделаю спрайты

2024-11-19 12:17 UTC, FireNameFN commented
> @Tornado-Technology @AwareFoxy
> 
> Прошу ревью кода и прототипов. На ошибки я открою его, когда доделаю спрайты

Ну да, ну да, пошёл я нафиг.

Я тебе сейчас такой разгромный ревью напишу.

2024-11-19 12:35 UTC, FireNameFN requested changes
Для начала.

2024-11-19 12:35 UTC, FireNameFN commented on Content.Server/Flash/FlashSystem.cs
> +using Content.Shared._CorvaxNext.Flash.Components; //CorvaxNext
Я бы предпочёл не писать комменты в юсингах. Тем более неправильные.

2024-11-19 12:35 UTC, FireNameFN commented on Content.Server/Flash/FlashSystem.cs
> +            //CorvaxNext duration modifier for resomi
Фигня в коммент, и не закрывается.

2024-11-19 12:35 UTC, FireNameFN commented on Content.Server/Flash/FlashSystem.cs
> +            if (TryComp<FlashModifierComponent>(target, out var CompUser))
```suggestion
            if (TryComp<FlashModifierComponent>(target, out var flashModifier))
```

2024-11-19 12:35 UTC, FireNameFN commented on Content.Shared/_CorvaxNext/Flash/Components/FlashModifierComponent.cs
Можно было разместить в Content.Server/Flash

2024-11-19 12:35 UTC, FireNameFN commented on Content.Server/_CorvaxNext/Speech/Components/ResomiAccentComponent.cs
> +}
```suggestion
public sealed partial class ResomiAccentComponent : Component;
```

2024-11-19 12:35 UTC, FireNameFN commented on Content.Server/_CorvaxNext/Speech/Components/ResomiAccentComponent.cs
> +/// </summary>
Чё?

2024-11-19 12:35 UTC, FireNameFN commented on Content.Server/_CorvaxNext/Speech/EntitySystems/ResomiAccentSystem.cs
> +        base.Initialize();
Нет нужды. Он пустой.

2024-11-19 12:35 UTC, FireNameFN commented on Content.Server/_CorvaxNext/Speech/EntitySystems/ResomiAccentSystem.cs
> +    private static readonly Regex RegexUpperEndX = new(@"\bX([\-|r|R]|\b)");
Они используются?

2024-11-19 12:35 UTC, FireNameFN commented on Content.Server/_CorvaxNext/Speech/EntitySystems/ResomiAccentSystem.cs
> +    [Dependency] private readonly IRobustRandom _random = default!; // Corvax-Localization
```suggestion
    [Dependency] private readonly IRobustRandom _random = default!;
```

2024-11-19 12:35 UTC, FireNameFN commented on Content.Shared/Weapons/Ranged/Events/GunRefreshModifiersEvent.cs
> +using Content.Shared.Weapons.Ranged.Components;
Хнык.

2024-11-19 12:35 UTC, FireNameFN commented on Content.Shared/Wieldable/Components/WieldableComponent.cs
> +    public EntityUid? User = null; //Corvax-Next
```suggestion
    public EntityUid? User; // Corvax-Next-Resomi
```

2024-11-19 12:35 UTC, FireNameFN commented on Content.Shared/Wieldable/WieldableSystem.cs
> +using Content.Shared._CorvaxNext.Resomi.Abilities; //Corvax-Next
То же самое.

2024-11-19 12:35 UTC, FireNameFN commented on Content.Shared/Wieldable/WieldableSystem.cs
> +            wield.Wielded && !HasComp<WeaponsUseInabilityComponent>(wield.User)) //Corvax-Next
```suggestion
            wield.Wielded && !HasComp<WeaponsUseInabilityComponent>(wield.User)) // Corvax-Next-Resomi
```

2024-11-19 12:35 UTC, FireNameFN commented on Content.Shared/Wieldable/WieldableSystem.cs
> +        component.User = user; //Corvax-Next
```suggestion
        component.User = user; // Corvax-Next-Resomi
```

2024-11-19 12:35 UTC, FireNameFN commented on Content.Server/_CorvaxNext/Resomi/Abilities/AgillitySkillSystem.cs
> +    private void SwitchAgility(Entity<AgillitySkillComponent> ent, ref SwitchAgillityActionEvent args)
Лучше не делать так. Назови ToggleAgility и сделай так, чтобы он принимал bool, включать ли.

2024-11-19 12:35 UTC, FireNameFN commented on Content.Server/_CorvaxNext/Resomi/Abilities/AgillitySkillSystem.cs
> +                continue;
Разкрафть.

2024-11-19 12:35 UTC, FireNameFN commented on Content.Shared/_CorvaxNext/Resomi/SharedResomi.cs
> +}
```suggestion
public sealed partial class SwitchAgillityActionEvent : InstantActionEvent;
```

2024-11-19 12:35 UTC, FireNameFN commented on Content.Shared/_CorvaxNext/Resomi/Abilities/WeaponsUseInabilityComponent.cs
> +}
```suggestion
public sealed partial class WeaponsUseInabilityComponent : Component;
```

2024-11-19 12:35 UTC, FireNameFN commented on Content.Shared/_CorvaxNext/Resomi/Abilities/SharedAgillitySkillSystem.cs
> +    public override void Initialize()
```suggestion
    protected const int BaseCollisionGroup = (int)(CollisionGroup.MobMask);
    
    public override void Initialize()
```

2024-11-19 12:35 UTC, FireNameFN commented on Content.Server/_CorvaxNext/Resomi/Abilities/AgillitySkillSystem.cs
> +public sealed class AgillitySkillSystem : SharedAgillitSkillSystem
```suggestion
namespace Content.Server._CorvaxNext.Resomi.Abilities;

public sealed class AgillitySkillSystem : SharedAgillitSkillSystem
```

2024-11-19 12:35 UTC, FireNameFN commented on Content.Server/_CorvaxNext/Resomi/Abilities/AgillitySkillSystem.cs
> +    private void ActivateAgility(Entity<AgillitySkillComponent> ent, Entity<BaseActionComponent> action)
```suggestion
    }
    
    private void ActivateAgility(Entity<AgillitySkillComponent> ent, Entity<BaseActionComponent> action)
```

2024-11-19 12:35 UTC, FireNameFN commented on Content.Server/_CorvaxNext/Resomi/Abilities/AgillitySkillSystem.cs
> +    private void DeactivateAgility(EntityUid uid, AgillitySkillComponent component, Entity<BaseActionComponent> action)
```suggestion
    }
    
    private void DeactivateAgility(EntityUid uid, AgillitySkillComponent component, Entity<BaseActionComponent> action)
```

2024-11-22 16:11 UTC, AwareFoxy approved these changes
норм

2024-11-22 16:11 UTC, AwareFoxy commented on Content.Server/Chat/ChatComponent.cs
> +/// Modifaer for entity to expand whisper radius
Modifaer

2024-11-23 00:42 UTC, pofitlo-Git commented
что?... у меня... нет компонента абилки со стороны сервера.... только в шейреде.....

2024-11-25 20:32 UTC, FireNameFN requested changes

2024-11-25 20:32 UTC, FireNameFN commented on Resources/Locale/ru-RU/species/species.ftl
> +species-name-resomi = Резоми
```suggestion
# Corvax-Next-Resomi-Start
species-name-resomi = Резоми
# Corvax-Next-Resomi-End
```

2024-11-25 20:32 UTC, FireNameFN commented on Content.Server/Chat/Systems/ChatSystem.cs
> +                || (listenerComp == null && data.Range <= WhisperClearRange)) //Corvax-Next-Resomi modifaer for whisper range
```suggestion
            if (data.Range <= (TryComp<ChatModifierComponent>(listener, out var modifier) ? modifier.WhisperListeningRange : WhisperClearRange)) // Corvax-Next-Resomi
```

И назови классы и поля, как тут.

2024-11-25 20:32 UTC, FireNameFN commented on Content.Server/Chat/ChatComponent.cs
> +    public int WhisperPersonalRange = 2;
```suggestion
    public int WhisperPersonalRange = SharedChatSystem.WhisperClearRange;
```

2024-11-25 20:32 UTC, FireNameFN commented on Content.Server/Chat/ChatComponent.cs
> +/// </summary>
Лучше удалить. Плохо написано.

2024-11-25 20:32 UTC, FireNameFN commented on Content.Shared/_CorvaxNext/Resomi/Abilities/SharedAgillitySkillSystem.cs
> +            return;
Разбей.

2024-11-25 20:32 UTC, FireNameFN commented on Content.Shared/_CorvaxNext/Resomi/Abilities/WeaponsUseInabilityComponent.cs
> +}
```suggestion
public sealed partial class WeaponsUseInabilityComponent : Component;
```

2024-11-25 20:32 UTC, FireNameFN commented on Content.Shared/_CorvaxNext/Resomi/Abilities/WeaponsUseInabilityComponent.cs
> +/// increases the spread, as if shooting was conducted from one hand
```suggestion
/// Increases the spread, as if shooting was conducted from one hand.
```

2024-11-25 22:39 UTC, AwareFoxy commented on Content.Shared/_CorvaxNext/Resomi/Abilities/SharedAgillitySkillSystem.cs
> +        if (!ent.Comp.Active || !ent.Comp.JumpEnabled)
Че за хуйню ты сделал, собирай назад
Три проверки зач плодить вместо одной

2024-11-25 22:40 UTC, FireNameFN commented on Content.Shared/_CorvaxNext/Resomi/Abilities/SharedAgillitySkillSystem.cs
> +        if (!ent.Comp.Active || !ent.Comp.JumpEnabled)
Иди нафиг, Авейр

2024-11-25 23:04 UTC, FireNameFN commented
Да не слушай его. Обратно разбивай.

2024-11-25 23:26 UTC, merged

2024-11-25 23:57 UTC, FireNameFN commented
Куда?! Ничего не готово. Наверное...