Добавить АПИИ
space-syndicate/space-station-14-next pull request #30
Opened 2024-11-09 06:46 UTC by FireNameFN

## Описание PR

Пока что секрет для непосвящённых.

## Ссылка на ветку

https://discord.com/channels/919301044784226385/1303844533695414353

**Список изменений**

Не забыть добавить cl.

2024-11-09 10:56 UTC, kosticia commented
Вор, у которого вместо нормальных целей - гриф игры одному игроку на ИИ? Такое нам надо

2024-11-09 11:28 UTC, foboscheshir commented
стелс антаг с голо :trollface:

2024-11-09 12:06 UTC, FireNameFN commented
Пипец, догадались посмотреть фтлку

2024-11-09 20:39 UTC, AwareFoxy requested changes
По коду всё ок

2024-11-10 02:06 UTC, AwareFoxy requested changes
в FTL с _CorvaxNext на _corvaxnext

2024-11-10 02:36 UTC, AwareFoxy approved these changes

2024-11-10 02:36 UTC, merged

2024-11-10 15:06 UTC, CaptainSqrBeard commented
сначала бы механ ИИ дождаться, прежде чем антагов подобных добавлять.

и возможно стоило реализовать это как цельку для трейтора, но хз