shaverma
space-syndicate/space-station-14-next pull request #39
Opened 2024-11-10 21:52 UTC by jailedfish

## Описание PR
Добавлена шаверма, готовящаяся в 2 этапа: 
* 5 секунд 2 мясо, тесто, томат
* 15 секунд шаверма

## Почему / Баланс
Попросили [здесь](https://discordapp.com/channels/919301044784226385/1304645328556916818) / готовая шаверма чуть лучше тако, так что баланс в норме

## Ссылка на ветку

https://discordapp.com/channels/919301044784226385/1304645328556916818

## Технические детали
* добавлена шаверма в двух вариантах (не испечённая и готовая) (./Resources/Prototypes/Entities/Objects/Consumable/Food/shaverma-unbaked.yml и ./Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/shaverma-baked.yml)
* добавлен её спрайт (./Resources/Textures/Objects/Consumable/Food/shavuha.rsi/) (лучше переделать)
* добавлен рецепт (./Resources/Prototypes/Recipes/Cooking/meal_recipes.yml)

## Медиа
./Resources/Textures/Objects/Consumable/Food/shavuha.rsi/baked.png
./Resources/Textures/Objects/Consumable/Food/shavuha.rsi/unbaked.png

**Список изменений**
:cl:
- add: Шавуха!

2024-11-10 21:56 UTC, jailedfish reviewed
Ну мне нравится, что

2024-11-10 22:20 UTC, FireNameFN requested changes

2024-11-10 22:20 UTC, FireNameFN commented on Resources/Prototypes/Recipes/Cooking/meal_recipes.yml
Кто-то сломал этот файл.

2024-11-10 22:20 UTC, FireNameFN commented on Resources/Prototypes/Recipes/Cooking/meal_recipes.yml
> +#Shaverma
```suggestion
# Corvax-Next-Shaverma-Start
```

2024-11-10 22:20 UTC, FireNameFN commented on Resources/Prototypes/Recipes/Cooking/meal_recipes.yml
>  #Bagels
```suggestion
# Corvax-Next-Shaverma-End
#Bagels
```

2024-11-10 22:20 UTC, FireNameFN commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/shaverma-baked.yml
> +# When adding new food also add to random spawner located in Resources\Prototypes\Entities\Markers\Spawners\Random\Food_Drinks\food_single.yml
Remove this.

2024-11-10 22:20 UTC, FireNameFN commented on Resources/Textures/Objects/Consumable/Food/shavuha.rsi/baked.png
Ничем не отличается от unbaked.

2024-11-10 22:20 UTC, FireNameFN commented on Resources/Textures/Objects/Consumable/Food/shavuha.rsi/meta.json
> +  "license": "MIT",
У Кмин на счёт лицензии спросить надо.

2024-11-10 22:22 UTC, jailedfish commented on Resources/Textures/Objects/Consumable/Food/shavuha.rsi/baked.png
Временно, пока пытаюсь нарисовать

2024-11-10 22:23 UTC, jailedfish commented on Resources/Prototypes/Recipes/Cooking/meal_recipes.yml
Где? когда?

2024-11-10 22:25 UTC, FireNameFN commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/shaverma-baked.yml
Не лучше создать один файл `shaverma.yml`, где будет и baked и unbaked?

2024-11-10 22:25 UTC, FireNameFN commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/shaverma-baked.yml
> +  name: шаверма
Наверное, перевод стоит делать в фтлках.

2024-11-10 22:26 UTC, jailedfish commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/shaverma-baked.yml
> +  name: шаверма
Наверное

2024-11-10 22:27 UTC, FireNameFN commented on Resources/Prototypes/Recipes/Cooking/meal_recipes.yml
Посмотри на diff

> Где? когда?

2024-11-10 22:28 UTC, jailedfish commented on Resources/Prototypes/Recipes/Cooking/meal_recipes.yml
у меня работает)

2024-11-10 22:41 UTC, jailedfish commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/shaverma-baked.yml
вопрос вкуса, думаю не стоит дискутировать

2024-11-10 22:54 UTC, FireNameFN commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/shaverma-baked.yml
Ну хотя бы в одну папку положить.

2024-11-10 22:54 UTC, FireNameFN commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/shaverma-baked.yml
> +  name: шаверма
Кмин сказал, что надо в фтлках.

2024-11-10 22:55 UTC, FireNameFN commented on Resources/Prototypes/Recipes/Cooking/meal_recipes.yml
![image](https://github.com/user-attachments/assets/31ed7545-a150-4b08-bcfa-741bd1da7b23)

2024-11-11 09:00 UTC, jailedfish commented on Resources/Textures/Objects/Consumable/Food/shavuha.rsi/meta.json
> +  "license": "MIT",
Пока можно оставить no license?

2024-11-11 09:01 UTC, jailedfish commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/shaverma-baked.yml
> +  name: шаверма
Готово, теперь в ftl

2024-11-11 13:49 UTC, AwareFoxy commented on Resources/Textures/Objects/Consumable/Food/shavuha.rsi/meta.json
> +  "license": "No license/unknown license",
Лицензия.

2024-11-11 14:02 UTC, jailedfish commented on Resources/Textures/Objects/Consumable/Food/shavuha.rsi/meta.json
> +  "license": "No license/unknown license",
Автор не отвечает

2024-11-11 14:48 UTC, jailedfish commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/shaverma-baked.yml
> +  name: шаверма
Нормик?

2024-11-11 16:26 UTC, jailedfish commented on Resources/Textures/Objects/Consumable/Food/shavuha.rsi/meta.json
> +  "license": "MIT",
Молчание - знак согласия

2024-11-11 16:49 UTC, jailedfish commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/shaverma-baked.yml
> +  name: шаверма
вроде работает

2024-11-11 17:00 UTC, jailedfish commented on Resources/Prototypes/Recipes/Cooking/meal_recipes.yml
всё поправил

2024-11-11 17:34 UTC, FireNameFN requested changes
Не забывай про то, что всё должно быть в `_CorvaxNext`.

2024-11-11 17:34 UTC, FireNameFN commented on Resources/Textures/Objects/Consumable/Food/shavuha.rsi/baked.png
Не в папке.

2024-11-11 17:34 UTC, FireNameFN commented on Resources/Textures/Objects/Consumable/Food/shavuha.rsi/meta.json
Не в папке.

2024-11-11 17:34 UTC, FireNameFN commented on Resources/Textures/Objects/Consumable/Food/shavuha.rsi/unbaked.png
Не в папке.

2024-11-11 17:34 UTC, FireNameFN commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/shaverma-baked.yml
Не в папке.

2024-11-11 17:34 UTC, FireNameFN commented on Resources/Prototypes/Entities/Objects/Consumable/Food/shaverma-unbaked.yml
Не в папке.

2024-11-11 17:34 UTC, FireNameFN commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/baked/shaverma-baked.ftl
Не забудь переместить, когда сместишь прототипы в папку.

2024-11-11 17:34 UTC, FireNameFN commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/shaverma-unbaked.ftl
Не забудь переместить, когда сместишь прототипы в папку.

2024-11-11 17:35 UTC, FireNameFN commented on Resources/Prototypes/Entities/Objects/Consumable/Food/shaverma-unbaked.yml
> +  id: Shaverma-unbaked
Название прототипа не должно таким быть.

2024-11-11 17:35 UTC, FireNameFN commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/shaverma-baked.yml
> +  id: Shaverma-baked
И это тоже.

2024-11-11 17:42 UTC, jailedfish commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/baked/shaverma-baked.ftl
не забуду

2024-11-11 18:32 UTC, jailedfish commented on Resources/Textures/Objects/Consumable/Food/shavuha.rsi/baked.png
fixed

2024-11-11 18:32 UTC, jailedfish commented on Resources/Textures/Objects/Consumable/Food/shavuha.rsi/meta.json
fixed

2024-11-11 18:33 UTC, jailedfish commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/shaverma-baked.yml
fixed

2024-11-11 18:33 UTC, jailedfish commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/baked/shaverma-baked.ftl
fixed

2024-11-11 18:33 UTC, jailedfish commented on Resources/Prototypes/Entities/Objects/Consumable/Food/shaverma-unbaked.yml
> +  id: Shaverma-unbaked
fixed

2024-11-11 18:33 UTC, jailedfish commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/shaverma-baked.yml
> +  id: Shaverma-baked
fixed

2024-11-11 18:33 UTC, jailedfish commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/shaverma-unbaked.ftl
fixed

2024-11-11 18:33 UTC, jailedfish commented on Resources/Prototypes/Entities/Objects/Consumable/Food/shaverma-unbaked.yml
fixed

2024-11-11 18:33 UTC, jailedfish commented on Resources/Textures/Objects/Consumable/Food/shavuha.rsi/unbaked.png
fixed

2024-11-11 18:34 UTC, jailedfish commented
всё поправил, вроде работает

2024-11-11 18:42 UTC, FireNameFN requested changes

2024-11-11 18:42 UTC, FireNameFN commented on Resources/Prototypes/_CorvaxNext/Recipes/Cooking/meal_recipes.yml
> +  id: RecipeShaverma-unbaked
Этот ID поправить.

2024-11-11 18:42 UTC, FireNameFN commented on Resources/Textures/_CorvaxNext/Objects/Consumable/Food/shavuha.rsi/baked.png
Текстура всё ещё одинаковая.

2024-11-11 18:42 UTC, FireNameFN commented on Resources/Prototypes/_CorvaxNext/Entities/Objects/Consumable/Food/shaverma.yml
> +      sprite: Objects/Consumable/Food/shavuha.rsi
Путь сломан.

2024-11-11 18:42 UTC, FireNameFN commented on Resources/Prototypes/Recipes/Cooking/meal_recipes.yml
Убери тогда изменения в этом файле.

2024-11-11 18:42 UTC, FireNameFN commented on Resources/Locale/ru-RU/_corvaxnext/entities/objects/consumable/food/shaverma-unbaked.ftl
Пустой файл. Удали.

2024-11-11 18:42 UTC, FireNameFN commented on Resources/Textures/_CorvaxNext/Objects/Consumable/Food/shavuha.rsi/meta.json
> +  "license": "No license/unknown license",
У Кмин спросить, какую лицензию ставить.

2024-11-11 18:45 UTC, jailedfish commented on Resources/Textures/_CorvaxNext/Objects/Consumable/Food/shavuha.rsi/baked.png
Йаргх, я не уметь рисовать, пока так потом может перерисую

2024-11-11 18:50 UTC, jailedfish commented on Resources/Textures/_CorvaxNext/Objects/Consumable/Food/shavuha.rsi/meta.json
> +  "license": "No license/unknown license",
Меня игнорят, пожалуйста попросите вы, если не сложно

2024-11-11 18:54 UTC, jailedfish commented on Resources/Locale/ru-RU/_corvaxnext/entities/objects/consumable/food/shaverma-unbaked.ftl
Иаргх, готово!

2024-11-11 18:54 UTC, jailedfish commented on Resources/Prototypes/Recipes/Cooking/meal_recipes.yml
Готово, кеп!

2024-11-11 18:54 UTC, jailedfish commented on Resources/Prototypes/_CorvaxNext/Entities/Objects/Consumable/Food/shaverma.yml
> +      sprite: Objects/Consumable/Food/shavuha.rsi
Починен

2024-11-11 18:55 UTC, jailedfish commented on Resources/Prototypes/_CorvaxNext/Recipes/Cooking/meal_recipes.yml
> +  id: RecipeShaverma-unbaked
Ирагх, есть!

2024-11-11 19:23 UTC, FireNameFN submitted a review, later dismissed

2024-11-11 19:23 UTC, FireNameFN commented on Resources/Prototypes/_CorvaxNext/Recipes/Cooking/meal_recipes.yml
> +# Corvax-Next-Shaverma-Start
Больше не нужно.

2024-11-11 19:23 UTC, FireNameFN commented on Resources/Prototypes/_CorvaxNext/Recipes/Cooking/meal_recipes.yml
> +# Corvax-Next-Shaverma-End
Больше не нужно.

2024-11-11 19:23 UTC, FireNameFN commented on Resources/Prototypes/_CorvaxNext/Recipes/Cooking/meal_recipes.yml
> +    Shaverma-unbaked: 1
Устаревший ID.

2024-11-11 19:23 UTC, FireNameFN commented on Resources/Textures/_CorvaxNext/Objects/Consumable/Food/shavuha.rsi/meta.json
> +  "license": "No license/unknown license",
```suggestion
  "license": "CC-BY-4.0",
```

2024-11-12 07:04 UTC, jailedfish commented
@FireNameFN надо ещё раз

2024-11-12 07:22 UTC, FireNameFN commented
Я изменил ченджлог, если что.

2024-11-12 07:22 UTC, FireNameFN commented
А по прототипам проблем не вижу. Ждём Кмин и Авейра.

2024-11-12 14:31 UTC, jailedfish commented
@AwareFoxy

2024-11-12 15:02 UTC, AwareFoxy commented
Дома буду посмотрю

2024-11-12 15:02 UTC, AwareFoxy commented
Дома буду посмотрю

2024-11-12 17:44 UTC, AwareFoxy requested changes
это исправить и можно мержить

2024-11-12 17:44 UTC, AwareFoxy commented on Resources/Locale/ru-RU/_corvaxnext/entities/objects/consumable/food/shaverma.ftl
> +ent-FoodShavermaUnbaked = заготовка шавермы
в ss14_ru/prototypes/_corvaxnext

2024-11-12 17:44 UTC, AwareFoxy commented on Resources/Locale/ru-RU/_corvaxnext/entities/objects/consumable/food/shaverma.ftl
> +    .desc = Пища богов.
убери 
![image](https://github.com/user-attachments/assets/4d16dc61-b418-49db-aefb-e8c2791780a5)

2024-11-12 17:46 UTC, jailedfish commented on Resources/Locale/ru-RU/_corvaxnext/entities/objects/consumable/food/shaverma.ftl
> +    .desc = Пища богов.
что это?

2024-11-12 20:59 UTC, jailedfish commented on Resources/Locale/ru-RU/_corvaxnext/entities/objects/consumable/food/shaverma.ftl
> +    .desc = Пища богов.
@AwareFoxy это что?

2024-11-12 21:41 UTC, jailedfish commented on Resources/Locale/ru-RU/_corvaxnext/entities/objects/consumable/food/shaverma.ftl
> +    .desc = Пища богов.
пофиксил

2024-11-13 02:56 UTC, AwareFoxy submitted a review, later dismissed

2024-11-13 06:54 UTC, jailedfish commented
@AwareFoxy мёрдж пж

2024-11-13 06:56 UTC, FireNameFN commented
> @AwareFoxy мёрдж пж

А чеки исправлять? У тебя там ещё какой-то rsi не используется.

2024-11-13 15:30 UTC, jailedfish commented
неиспользуемый rsi поправил, а тесты и на чистом билде не запускаются

2024-11-13 15:30 UTC, jailedfish commented
@AwareFoxy

2024-11-13 16:59 UTC, FireNameFN commented on Resources/Prototypes/_CorvaxNext/Entities/Objects/Consumable/Food/shaverma.yml
У этого файла сломаны отступы.

2024-11-13 17:16 UTC, jailedfish commented
ну всё, самое время апрувить

2024-11-13 17:18 UTC, AwareFoxy commented
Выглядит вкусно, пахнет вкусно, кушать можно.

2024-11-13 17:19 UTC, merged

2024-11-13 19:16 UTC, hiucko commented
Легенда ахаха 🥇 , спасибо за шаурму