Traits for roundstart species size
space-syndicate/space-station-14-next pull request #4
Opened 2024-09-11 10:58 UTC by KillanGenifer

## Описание PR
Добавляет две новые черты внешности в виде высокого/низкого роста. 

Вся смелая часть кода была взята с репы фронтира и слегка отредактировано под нас. Изменён класс Server/Cloning/CloneSystem, чтобы черты оставались после клонирования.

**Медиа**
![image](https://github.com/user-attachments/assets/3ea504b2-2538-40f9-820b-9d90af7f6b01)

2024-09-11 13:43 UTC, Votknyl commented
Прикольно, дварфы но люди? эльфы но дварфы?

2024-09-11 14:06 UTC, Vonsant commented
Код под лицензией AGPL v3, соре но соре, его приём будем нарушать лицензию.

2024-09-11 14:07 UTC, Emechitas commented
> Код под лицензией AGPL v3, соре но соре, его приём будем нарушать лицензию.

![gosling](https://github.com/user-attachments/assets/24fcdbea-0ba8-4706-81c1-807d2f200d11)

2024-09-11 14:08 UTC, Vonsant commented
> > Код под лицензией AGPL v3, соре но соре, его приём будем нарушать лицензию.
> 
> ![gosling](https://private-user-images.githubusercontent.com/174242828/366491424-24fcdbea-0ba8-4706-81c1-807d2f200d11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNjM5NzgsIm5iZiI6MTcyNjA2MzY3OCwicGF0aCI6Ii8xNzQyNDI4MjgvMzY2NDkxNDI0LTI0ZmNkYmVhLTBiYTgtNDcwNi04MWMxLTgwN2QyZjIwMGQxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQxNDA3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2UzYTY1ZGU5NTZjODFhMzg1M2Q1ZDFhZGZkNWQzYzczOWEwYzQzN2Y0N2U1Y2VhNzIxZTJkYTczY2Q3Y2ZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._-wvt8FCYgwokfxgQK51cTBeMda5GDZk9Nyv-awD3CE)

Нарушение лицензии - нарушение правила 1.2 правил хаба.

2024-09-11 14:17 UTC, lzk228 requested changes

2024-09-11 14:17 UTC, lzk228 commented on Content.Server/Cloning/CloningSystem.cs
> +
```suggestion
        [Dependency] private readonly ISerializationManager _serialization = default!; // Corvax-Next

```

2024-09-11 14:17 UTC, lzk228 commented on Content.Server/Cloning/CloningSystem.cs
> +            }
```suggestion
            // Corvax-Next-Start
            foreach (var comp in EntityManager.GetComponents(bodyToClone))
            {
                if (comp is ITransferredByCloning)
                {
                    var copy = _serialization.CreateCopy(comp, notNullableOverride: true);
                    copy.Owner = mob;
                    EntityManager.AddComponent(mob, copy, overwrite: true);
                }
            }
            // Corvax-Next-End
```

2024-09-11 14:17 UTC, lzk228 commented on Resources/Prototypes/Entities/Mobs/Species/base.yml
> +    shortscale: 0.90
```suggestion
  # Corvax-Next-Start
  - type: SizeAttributeWhitelist
    tall: true
    tallscale: 1.1
    short: true
    shortscale: 0.90
  # Corvax-Next-End
```

2024-09-11 14:17 UTC, lzk228 commented on Resources/Prototypes/Entities/Mobs/Species/dwarf.yml
> +    short: false
```suggestion
  # Corvax-Next-Start
  - type: SizeAttributeWhitelist
    tall: false
    short: false
   # Corvax-Next-End
```

2024-09-11 14:17 UTC, lzk228 commented on Resources/Prototypes/Traits/categories.yml
> +  maxTraitPoints: 1
это перенести в директорию Corvax

2024-09-11 14:17 UTC, lzk228 commented on Resources/Prototypes/Traits/sizeattribute.yml
это перенести в директорию Corvax

2024-09-11 14:18 UTC, Vonsant commented
@lzk228 Зря стараешься, это чужой код нарушающий лицензию.

2024-09-11 14:30 UTC, lzk228 commented
ну не мне же его мёржить, у меня и прав то нет

2024-09-11 17:32 UTC, KillanGenifer commented
Вроде подправил. Если этот ПР внатуре нарушает правила оффов - перепишу с нуля по другому.

2024-09-11 17:39 UTC, Morb0 commented
> Вроде подправил. Если этот ПР внатуре нарушает правила оффов - перепишу с нуля по другому.

Переписывай

2024-09-11 21:02 UTC, MetalSage commented
> Код под лицензией AGPL v3, соре но соре, его приём будем нарушать лицензию.

AGPL v3 свободная лицензия, единственное и главное ограничение, весь репозиторий в котором используется код AGPL v3 должен быть лицензирован так же под AGPL v3 и быть полностью открыт

2024-09-11 21:50 UTC, Vonsant commented
> > Код под лицензией AGPL v3, соре но соре, его приём будем нарушать лицензию.
> 
> AGPL v3 свободная лицензия, единственное и главное ограничение, весь репозиторий в котором используется код AGPL v3 должен быть лицензирован так же под AGPL v3 и быть полностью открыт

Да, ты прав. И увы, этот репозиторий под MIT и будет всегда под MIT.

2024-09-12 11:50 UTC, lzk228 commented
имхо это очень странно делать это через два булеана в компоненте

2024-09-12 11:54 UTC, KillanGenifer commented
> имхо это очень странно делать это через два булеана в компоненте

Это сделано, чтобы при инициализации компонента выбиралось, в какую сторону изменять рост куклы.

2024-09-12 13:21 UTC, whateverusername0 commented
вывод - просто поменяйте лицензию на AGPLv3 и добавьте MIT как сайд
нахуй париться когда решение на поверхности

2024-09-12 13:26 UTC, Vonsant commented
> вывод - просто поменяйте лицензию на AGPLv3 и добавьте MIT как сайд нахуй париться когда решение на поверхности

Уже решено сверху, другой лицензии не будет.

2024-09-15 10:12 UTC, ficcialfaint requested changes
Везде должны быть [file-scoped namespaces](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces)

2024-09-15 10:12 UTC, ficcialfaint commented on Content.Server/Traits/Assorted/HeightComponent.cs
> +        [DataField("tall")]
```suggestion
        [DataField]
```

2024-09-15 10:12 UTC, ficcialfaint commented on Content.Server/Traits/Assorted/HeightComponent.cs
> +        [DataField("short")]
```suggestion
        [DataField]
```

2024-09-15 10:12 UTC, ficcialfaint commented on Content.Server/Traits/Assorted/HeightComponent.cs
> +    }
```suggestion
    }
```

2024-09-15 10:12 UTC, ficcialfaint commented on Content.Server/Traits/Assorted/HeightSystem.cs
> +                            throw new NotImplementedException();
```suggestion
                            break;
```

2024-09-15 10:12 UTC, ficcialfaint commented on Content.Server/Traits/Assorted/HeightSystem.cs
> +            if (TryComp<HeightTraitBlacklistComponent>(uid, out var comp))
```suggestion
            if (HasComp<HeightTraitBlacklistComponent>(uid))
```

2024-09-15 10:12 UTC, ficcialfaint commented on Content.Server/Traits/Assorted/HeightSystem.cs
> +            var appearance = _entityManager.System<AppearanceSystem>();
Почему это не может быть `[Dependency]` вместо использования `.System()`?

2024-09-15 10:12 UTC, ficcialfaint commented on Content.Server/Traits/Assorted/HeightSystem.cs
> +            var appearanceComponent = _entityManager.EnsureComponent<AppearanceComponent>(uid);
`EnsureComp`?

2024-09-15 10:12 UTC, ficcialfaint commented on Content.Server/Traits/Assorted/HeightSystem.cs
> +            if (_entityManager.TryGetComponent(uid, out FixturesComponent? manager))
инвертируй if-блок + `TryComp`

2024-09-15 10:12 UTC, ficcialfaint commented on Content.Server/Traits/Assorted/HeightSystem.cs
> +        private void Scale(EntityUid uid, float scale)
```suggestion
        }
        
        private void Scale(EntityUid uid, float scale)
```

2024-09-17 15:07 UTC, KillanGenifer commented on Content.Server/Traits/Assorted/HeightSystem.cs
> +            var appearance = _entityManager.System<AppearanceSystem>();
Разве это критично важно? Часть кода изменения размера была взята из репы движка, где команда /scale

2024-09-17 15:11 UTC, ficcialfaint commented on Content.Server/Traits/Assorted/HeightSystem.cs
> +            var appearance = _entityManager.System<AppearanceSystem>();
ну ты каждый раз про вызове метода Scale получаешь систему вместо того, чтобы один раз инжектнуть Dependency

2024-09-17 15:36 UTC, KillanGenifer commented on Content.Server/Traits/Assorted/HeightSystem.cs
> +            var appearance = _entityManager.System<AppearanceSystem>();
> ну ты каждый раз про вызове метода Scale получаешь систему вместо того, чтобы один раз инжектнуть Dependency

В целом, логично. Тогда отправлю комит с новым кодом на основе всех названных ошибок. Я прост не очень силён в кодинге на шарпе, особенно в связке с таким большим проектом.

2024-09-21 10:19 UTC, Tornado-Technology requested changes

2024-09-21 10:19 UTC, Tornado-Technology commented on Content.Server/Traits/Assorted/HeightComponent.cs
> +        public readonly float TallScale = 1.10f;
Сделай это череp [DataField]

2024-09-21 10:19 UTC, Tornado-Technology commented on Content.Server/Traits/Assorted/HeightComponent.cs
> +    public sealed partial class HeightComponent : Component
Переменная `isShort` и `isTall` идея плохая, лучше сделай прототипы роста, или хотя бы enum значение

2024-09-21 10:19 UTC, Tornado-Technology commented on Content.Server/Traits/Assorted/HeightSystem.cs
> +{
Этот блок лишний

2024-09-21 10:19 UTC, Tornado-Technology commented on Content.Server/Traits/Assorted/HeightSystem.cs
> +            if (component.Short)
Как говорил выше, реализация отвратительная

2024-09-21 10:19 UTC, Tornado-Technology commented on Content.Server/Traits/Assorted/HeightSystem.cs
> +            SubscribeLocalEvent<HeightComponent, ComponentStartup>(InitComponent);
Убирать изменение роста при удалении компонента

2024-09-21 10:19 UTC, Tornado-Technology commented on Content.Shared/Traits/Assorted/HeightTraitBlacklistComponent.cs
> +    { }
Этот блок лишний просто ставь `;`

2024-09-21 10:19 UTC, Tornado-Technology commented on Resources/Prototypes/Corvax/Traits/categories.yml
> +  name: Рост
используй `loc` файлы

2024-09-21 10:19 UTC, Tornado-Technology commented on Resources/Prototypes/Corvax/Traits/height.yml
используй `loc` файлы

2024-09-21 10:19 UTC, Tornado-Technology commented on Resources/Prototypes/Traits/categories.yml
Убери не нужные изменения

2024-09-21 11:10 UTC, Vonsant commented
Лицензию сменили кстати.

2024-09-24 14:47 UTC, JerryImMouse commented
ебать вы с Торнадо человека обработали 😨

2024-11-27 00:05 UTC, FireNameFN commented
Так, это закрывать хотели.

2024-11-27 02:42 UTC, KillanGenifer commented
> Так, это закрывать хотели.

Поч, я ревертнул до первой фронтировской версии, фиксанул ошибки и докинул функцию отката роста при удалении компонена. Код то полностью рабочий

2024-11-29 02:47 UTC, Tornado-Technology commented
> > Так, это закрывать хотели.
> 
> Поч, я ревертнул до первой фронтировской версии, фиксанул ошибки и докинул функцию отката роста при удалении компонена. Код то полностью рабочий

Ты решил проблемы описаные в ревью? Нет. Мерджа не будет

2024-11-29 07:58 UTC, KillanGenifer commented
> > > Так, это закрывать хотели.
> > 
> > 
> > Поч, я ревертнул до первой фронтировской версии, фиксанул ошибки и докинул функцию отката роста при удалении компонена. Код то полностью рабочий
> 
> Ты решил проблемы описаные в ревью? Нет. Мерджа не будет

Решил их, вот и запросил повторный ревью у тебя

2025-01-05 14:00 UTC, Tornado-Technology commented
> > > > Так, это закрывать хотели.
> > > 
> > > 
> > > Поч, я ревертнул до первой фронтировской версии, фиксанул ошибки и докинул функцию отката роста при удалении компонена. Код то полностью рабочий
> > 
> > 
> > Ты решил проблемы описаные в ревью? Нет. Мерджа не будет
> 
> Решил их, вот и запросил повторный ревью у тебя

Если ты ещё не понял. Компонент порождает состояние когда одновременно персонаж будет высоким и низким. Теперь опиши как это работает, и почему это хорошо.

2025-01-16 15:42 UTC, KillanGenifer commented
> > > > > Так, это закрывать хотели.
> > > > 
> > > > 
> > > > Поч, я ревертнул до первой фронтировской версии, фиксанул ошибки и докинул функцию отката роста при удалении компонена. Код то полностью рабочий
> > > 
> > > 
> > > Ты решил проблемы описаные в ревью? Нет. Мерджа не будет
> > 
> > 
> > Решил их, вот и запросил повторный ревью у тебя
> 
> Если ты ещё не понял. Компонент порождает состояние когда одновременно персонаж будет высоким и низким. Теперь опиши как это работает, и почему это хорошо.

Невозможно такого добиться. В редакторе доступен максимум один поинт, что позволяет выбрать только 1 тип размера. А если каким-то боком это и получится, то в системе есть условие, что при инициализации компача первым пойдёт длинный тип.

2025-04-10 07:56 UTC, closed without merging