Извлекаемые чертежи
space-syndicate/space-station-14-next pull request #47
Opened 2024-11-13 16:40 UTC by CaptainSqrBeard

## Описание PR
В интерфейсе автолата появилась кнопка для быстрого извлечения вставленных чертежей.

## Почему / Баланс
Удобный способ вытащить чертежи из автолата. QoL фича. Потребуется для удобства будущего механа

## Ссылка на ветку
Ветка: https://discord.com/channels/919301044784226385/1305590351607627796
Самый актуальный дизайн: https://discord.com/channels/919301044784226385/1305590351607627796/1306241056299421839

## Технические детали
- Игра теперь сообщает клиентам, есть ли в протолате какие-либо чертежи.
- Также изменения в интерфейсе лата: добавление кнопки. Кнопка скрывается, если у лата нету компонента `BlueprintReceiver`. Ну и собственно логика кнопки.

## Медиа
![image](https://github.com/user-attachments/assets/5094d125-ce6d-4d5d-ba14-ada3b9ae3d38)
![image](https://github.com/user-attachments/assets/29be5f7c-7e6b-4e88-8d10-afecf6cc8fa3)

## Критические изменения
\-

**Список изменений**
:cl: csqrb
- tweak: Из автолата теперь можно извлечь чертежи при помощи кнопки в интерфейсе.

2024-11-13 17:27 UTC, AwareFoxy requested changes
Изменяй и можно мерджить.

2024-11-13 17:27 UTC, AwareFoxy commented on Content.Client/Lathe/UI/LatheBoundUserInterface.cs
> +                    _menu?.UpdateBlueprintEjectButton(msg.HasAnyBlueprints);
```suggestion
                    _menu?.UpdateBlueprintEjectButton(msg.HasAnyBlueprints);             // Corvax-Next-BlueprintEject
```

2024-11-13 17:27 UTC, AwareFoxy commented on Content.Client/Lathe/UI/LatheMenu.xaml.cs
> +using Content.Shared.Research.Components;
```suggestion
using Content.Shared.Research.Components;            // Corvax-Next-BlueprintEject
```

2024-11-13 17:27 UTC, AwareFoxy commented on Content.Server/Lathe/LatheSystem.cs
> +using Content.Shared.Research.Systems;
// Corvax-Next-BlueprintEject

2024-11-13 17:27 UTC, AwareFoxy commented on Content.Shared/Lathe/LatheMessages.cs
> +    public bool HasAnyBlueprints;
// Corvax-Next-BlueprintEject

2024-11-13 17:27 UTC, AwareFoxy commented on Content.Shared/Lathe/LatheMessages.cs
> +    public LatheUpdateState(List<ProtoId<LatheRecipePrototype>> recipes, List<LatheRecipePrototype> queue, LatheRecipePrototype? currentlyProducing = null, bool hasAnyBlueprints = false)
// Corvax-Next-BlueprintEject

2024-11-13 17:27 UTC, AwareFoxy commented on Content.Shared/Lathe/LatheMessages.cs
> +        HasAnyBlueprints = hasAnyBlueprints;
// Corvax-Next-BlueprintEject

2024-11-14 03:24 UTC, CaptainSqrBeard commented
Кое-что надо улучшить

2024-11-14 05:31 UTC, CaptainSqrBeard commented
Ладно, на самом деле не надо :)

2024-11-15 11:44 UTC, AwareFoxy approved these changes
norm

2024-11-15 19:16 UTC, Vonsant commented
Выглядит Ок.

2024-11-16 17:04 UTC, Tornado-Technology submitted a review, later dismissed
Если хочешь, кинь оффам, тема годная

2024-11-17 07:19 UTC, FireNameFN requested changes

2024-11-17 07:19 UTC, FireNameFN commented on Content.Server/Lathe/LatheSystem.cs
> +        [Dependency] private readonly BlueprintSystem _blueprints = default!; // Corvax-Next
```suggestion
        [Dependency] private readonly BlueprintSystem _blueprints = default!; // Corvax-Next-BlueprintEject
```
```suggestion
        [Dependency] private readonly BlueprintSystem _blueprints = default!;
```

2024-11-18 19:35 UTC, AwareFoxy commented on Content.Server/Lathe/LatheSystem.cs
> +        [Dependency] private readonly BlueprintSystem _blueprints = default!;
```suggestion
        [Dependency] private readonly BlueprintSystem _blueprints = default!; // Corvax-Next-BlueprintEject
```

2024-11-18 19:36 UTC, AwareFoxy approved these changes

2024-11-18 19:49 UTC, AwareFoxy commented
тесты проходят, кушать тоже можно

2024-11-18 19:49 UTC, merged