АПИИ 3
space-syndicate/space-station-14-next pull request #52
Opened 2024-11-14 08:00 UTC by FireNameFN

## Описание PR

Поправил некоторые баги, которые были от компонентов вора. Теперь АПИИ даётся имплант хранилища, в котором содержится его начальное снаряжение. Добавлен глушитель связи.

## Ссылка на ветку

https://discord.com/channels/919301044784226385/1303844533695414353

**Список изменений**

:cl:
- tweak: Теперь у АПИИ сразу появляется имплант хранилища с вещами в нём.
- tweak: Теперь у АПИИ есть глушитель связи.

2024-11-16 17:14 UTC, Tornado-Technology requested changes
ещё неприятно что он связан с вором, но без переписи вора не выйдет сделать это круто, а перепись вора придет к проблемам с мерджем, так что сойдет

2024-11-16 17:14 UTC, Tornado-Technology commented on Content.Server/Thief/Systems/ThiefBeaconSystem.cs
> +        if (mind == null || !_roles.MindHasRole<ThiefRoleComponent>(mind.Value) && !_roles.MindHasRole<ApiRoleComponent>(mind.Value)) // Corvax-Next-Api
Этот подход крайне плох, надо придумать как это исправить

2024-11-16 17:14 UTC, Tornado-Technology commented on Content.Server/Thief/Systems/ThiefBeaconSystem.cs
> +        if (mind == null || !_roles.MindHasRole<ThiefRoleComponent>(mind.Value) && !_roles.MindHasRole<ApiRoleComponent>(mind.Value)) // Corvax-Next-Api
Как вариант добавление EntityWhiteList для данной системы, или что то подобное. Или комопонент, который дается в майнд и позволяет пользоваться беаканом

2024-11-16 17:17 UTC, FireNameFN commented
> ещё неприятно что он связан с вором, но без переписи вора не выйдет сделать это круто, а перепись вора придет к проблемам с мерджем, так что сойдет

Сказал "сойдёт" и нажал чендж реквест?

2024-11-17 00:23 UTC, CaptainSqrBeard commented
# Тестирование
## Разное
- Зависимость от карты: На некоторых картах замапленны интеллкарты, в том числе они могут быть замапленны прям на спутнике ИИ. На тушкане вообще ИИ в телекоммах сидит
- АПИИ правильно показывается в манифесте раунда, но не в манифесте игроков. Там он показывается как простой вор
- АПИИ не может захватить ИИ без игрока
- У украденной ИИ есть доступ к двоичному каналу. Не уверен, проблема это или нет.

## Снаряжение
- Тулбокс АПИИ невозможно отличить от тулбокса вора в спавн меню
- Маяки и тулбоксы АПИИ и вора в целом внешне идентичны (как раз работа для спрайтеров :trollface:)
- У игрока нету выбора между наборами в тулбоксе, при этом сами наборы схожи наборам вора. Было-бы неплохо подумать над новыми наборами и каким-то разнообразием выбора.

![api_diff](https://github.com/user-attachments/assets/ff3b2dbe-bf6c-483f-bcd7-e919614da0fa)

2024-11-18 12:59 UTC, FireNameFN commented
> АПИИ не может захватить ИИ без игрока

АПИИ не будет спавниться, когда нет ЦИИ.
> У украденной ИИ есть доступ к двоичному каналу. Не уверен, проблема это или нет.

У АПИИ есть глушилка.
> У игрока нету выбора между наборами в тулбоксе, при этом сами наборы схожи наборам вора. Было-бы неплохо подумать над новыми наборами и каким-то разнообразием выбора.

Тулбокс его будет ещё переработан.

2024-11-19 12:42 UTC, Tornado-Technology approved these changes

2024-11-20 09:55 UTC, merged