Zaverton (shawarma)
space-syndicate/space-station-14-next pull request #56
Opened 2024-11-14 16:49 UTC by VulfiMoon

## Описание PR
Добавил завертон (русская шаурма) и лаваш к нему. 

Рецепт завертона:                                                
Лаваш - 1 шт.                                                         
Ломтик лука - 2 шт.                                               
Поджаренная куриная котлета - 2 шт.                 
Морковь - 2 шт
Томат - 1 шт.
Кетчунез - 5 ед.
Подогреть в микроволновке на 10 сек.

Рецепт лаваша:
Плоское тесто (скалкой по тесту) - 1 шт.
Соль - 5 ед. 
Подогреть в микроволновке 5 сек.

## Почему / Баланс
Вкусная еда для иммигрантов станции

## Медиа

https://github.com/user-attachments/assets/d2baada1-77e4-44e3-84f4-c5be65a5cad2

## Критические изменения

**Список изменений**

:cl:
- add: Завертон с курицей
- add: Лаваш

2024-11-14 20:42 UTC, jailedfish commented
Наверное, перевод стоит делать в фтлках. © @FireNameFN

2024-11-14 22:00 UTC, VulfiMoon commented
> Наверное, перевод стоит делать в фтлках. © @FireNameFN

О чем ты?
Я сделал только фтлку для вкуса и все, не вижу надобность делать для всего это

2024-11-14 22:26 UTC, jailedfish commented
> > Наверное, перевод стоит делать в фтлках. © @FireNameFN
> 
> О чем ты? Я сделал только фтлку для вкуса и все, не вижу надобность делать для всего это

не знаю, но @FireNameFN мне сказал делать всё в ftl, не думаю, что это обязательно, но лучше сделать, чтобы потом локализовать проще было (нет, ну а вдруг переведут твою шавуху на английский)

2024-11-15 03:33 UTC, VulfiMoon commented
> > > Наверное, перевод стоит делать в фтлках. © @FireNameFN
> > 
> > 
> > О чем ты? Я сделал только фтлку для вкуса и все, не вижу необходимости делать это для всего
> 
> не знаю, но @FireNameFN сказал мне делать всё в ftl, не думаю, что это обязательно, но лучше сделать так, чтобы потом было проще локализовать (нет, ну а вдруг твою шавуху переведут на английский)

Не думаю, что английским билдам нужна шаурма ))

2024-11-15 05:01 UTC, FireNameFN requested changes

2024-11-15 05:01 UTC, FireNameFN commented on Resources/Textures/_CorvaxNext/Objects/Consumable/Food/shawarma.rsi/meta.json
> +            "name": "shawarma-base"
```suggestion
            "name": "shawarma_base"
```

2024-11-15 05:01 UTC, FireNameFN commented on Resources/Textures/_CorvaxNext/Objects/Consumable/Food/shawarma.rsi/shawarma-base.png
Нижнее подчёркивание, а не тире.

2024-11-15 05:01 UTC, FireNameFN commented on Resources/Prototypes/_CorvaxNext/Entities/Objects/Consumable/Food/shawarma.yml
> +    - state: shawarma-base
```suggestion
    - state: shawarma_base
```

2024-11-15 05:01 UTC, FireNameFN commented on Resources/Prototypes/_CorvaxNext/Entities/Objects/Consumable/Food/shawarma.yml
> +#SHAWARMA!! Net, zaverton!
```suggestion
```

2024-11-15 10:37 UTC, VulfiMoon commented on Resources/Textures/_CorvaxNext/Objects/Consumable/Food/shawarma.rsi/shawarma-base.png
Везде через тире делается

2024-11-15 10:38 UTC, VulfiMoon commented on Resources/Prototypes/_CorvaxNext/Entities/Objects/Consumable/Food/shawarma.yml
> +          Quantity: 4
База еды

2024-11-15 10:45 UTC, FireNameFN commented on Resources/Prototypes/_CorvaxNext/Entities/Objects/Consumable/Food/shawarma.yml
> +          Quantity: 4
Ну так зачем ещё раз объявил? Ошибки будут.

2024-11-15 10:46 UTC, FireNameFN commented on Resources/Textures/_CorvaxNext/Objects/Consumable/Food/shawarma.rsi/shawarma-base.png
Нигде.

2024-11-15 12:15 UTC, jailedfish commented
Я же говорил

2024-11-17 19:50 UTC, VulfiMoon commented on Resources/Prototypes/_CorvaxNext/Entities/Objects/Consumable/Food/shawarma.yml
> +          Quantity: 4
> Ну так зачем ещё раз объявил? Ошибки будут.

Нету ошибок

2024-11-17 19:51 UTC, VulfiMoon commented on Resources/Prototypes/_CorvaxNext/Entities/Objects/Consumable/Food/shawarma.yml
> +          Quantity: 4
Объявлено в parent

2024-11-20 07:50 UTC, seeitsthem commented on Resources/Locale/ru-RU/ss14-ru/prototypes/_corvaxnext/entities/objects/consumable/food/shawarma.ftl
Точку в конце описания поставь.

2024-11-20 07:51 UTC, seeitsthem commented on Resources/Prototypes/_CorvaxNext/Entities/Objects/Consumable/Food/shawarma.yml
> +  name: Лаваш
"лаваш" должен быть маленькой буквы.

2024-11-20 07:51 UTC, seeitsthem commented on Resources/Prototypes/_CorvaxNext/Entities/Objects/Consumable/Food/shawarma.yml
> +  description: Тонкая воздушная лепешка. Йа твой лавашъ кетчуп мазаль
Поставь точку в конце описания.

2024-11-20 07:57 UTC, seeitsthem commented on Resources/Prototypes/_CorvaxNext/Entities/Objects/Consumable/Food/shawarma.yml
> +  name: Куриный завертон
"завертон с курицей", а не "Куриный завертон". В будущем будут добавлены другие рецепты и с ними такая форма словосочетания будет смотреться глупо. Например, "шивный завертон". Название предмета также должно быть с маленькой буквы.

2024-11-20 07:58 UTC, seeitsthem commented on Resources/Prototypes/_CorvaxNext/Entities/Objects/Consumable/Food/shawarma.yml
> +  description: Это шаурма! Или шаверма?.. Настолько сочная, что лаваш снизу подтекает.
Слово "лаваш" можно убрать ;-)

2024-11-20 09:13 UTC, seeitsthem requested changes

2024-11-20 09:13 UTC, seeitsthem commented on Resources/Locale/ru-RU/ss14-ru/prototypes/_corvaxnext/entities/objects/consumable/food/shawarma.ftl
> +food-chicken-shawarma-eat = На вкус как еда с вокзала
Вкусы в остальной игре устроены не так. Перед вкусом любой еды предустановлено "Ням. На вкус", а затем уже дальше идёт "как вставьте описание вкуса".

2024-11-20 09:16 UTC, jailedfish commented on Resources/Prototypes/_CorvaxNext/Entities/Objects/Consumable/Food/shawarma.yml
> +  description: Тонкая воздушная лепешка. Йа твой лавашъ кетчуп мазаль
Чем тебе буква ё не угодила?

2024-11-20 12:49 UTC, seeitsthem commented on Resources/Prototypes/_CorvaxNext/Entities/Objects/Consumable/Food/shawarma.yml
> +  description: Тонкая воздушная лепешка. Йа твой лавашъ кетчуп мазаль
> Чем тебе буква ё не угодила?

Тем, что её там не было.

2025-01-17 16:34 UTC, closed without merging