[Port] Advanced Body Bags
space-syndicate/space-station-14-next pull request #57
Opened 2024-11-14 18:16 UTC by PuroSlavKing

## Описание PR

Taken from: https://github.com/WWhiteDreamProject/wwdpublic/pull/120

- Добавлено 5 новых мешков для тел, они печатаются в медфабе. 
- - Блюспейс мешок, что логично вмещает в себя больше чем обычные мешки, 1 -> 50.
- - Противорадиационный мешок не позволяет чему-то радиоактивному облучать всё вокруг.
- - Мешок синдиката, вмещает больше обычного, 1 -> 3.
- - Тюремный мешок и мешок НТ не имеют никаких особенностей.
- - - Коробка с тюремными мешками появляется в шкафу смотрителя и бригмедика.
- - - Коробка с противорадиационными мешками появляется в шкафу НРа.
- - Мешок синдиката (Второй слева) не исследуется, он открывается емагом медфаба.

## Почему / Баланс

## Ссылка на ветку

## Технические детали

## Медиа

![image](https://github.com/user-attachments/assets/f1542240-0237-4290-845a-2b5ffbdd556c)

## Критические изменения

**Список изменений**
:cl: PuroSlavKing
- add: Добавлено 5 новых вариаций мешков для - тел.

2024-11-14 18:53 UTC, lzk228 requested changes
не заполнил почему баланс

2024-11-14 20:18 UTC, PuroSlavKing commented
> не заполнил почему баланс

потому-что что в мешочке весит

2024-11-15 04:49 UTC, AwareFoxy approved these changes

2024-11-15 05:20 UTC, FireNameFN commented
Нужен респрайт.

2024-11-16 04:04 UTC, AwareFoxy commented
Тесты

2024-11-16 04:46 UTC, PuroSlavKing commented
> Тесты

Так нам написано же из-за чего ошибка (Не меня)

2024-11-18 19:27 UTC, merged