Фикс следов
space-syndicate/space-station-14-next pull request #59
Opened 2024-11-15 14:40 UTC by CaptainSqrBeard

## Описание PR
Добавлена локализация следам. При чистке следов также чистятся другие следы вокруг.

## Почему / Баланс
Так должно было быть изначально

## Ссылка на ветку
https://discord.com/channels/919301044784226385/1306685097772322840

## Технические детали
- Портированные модификации системы `Server.AbsorbentSystem`
- Я соединил if-ы обратно

## Медиа
![image](https://github.com/user-attachments/assets/9aa17756-bc16-4bcf-83ad-99f6a519aeda)

## Критические изменения
\-

**Список изменений**
:cl: csqrb
- fix: При чистке следов также будут чистится следы вокруг
- add: Добавлена локализация следам

2024-11-15 15:10 UTC, CaptainSqrBeard commented on Resources/Locale/ru-RU/ss14-ru/prototypes/_corvaxnext/entities/objects/effects/footstep.ftl
> +.desc = След из жидкости.
код пишешь, за тебя ещё и допиливают 😃

2024-11-15 19:46 UTC, Vonsant commented
@CaptainSqrBeard видеозапись приложи.

2024-11-15 20:03 UTC, CaptainSqrBeard commented
> @CaptainSqrBeard видеозапись приложи.

добавил

2024-11-15 21:29 UTC, FireNameFN commented
Много, что не так в этом ПРе. Обсудим ещё.

2024-11-15 21:46 UTC, CaptainSqrBeard commented
> Много, что не так в этом ПРе. Обсудим ещё.

ну, напишешь под постом если что

2024-11-16 11:26 UTC, AwareFoxy submitted a review, later dismissed

2024-11-16 11:28 UTC, FireNameFN commented
Какой аппрув? Ты вообще его читал? @AwareFoxy

2024-11-16 11:29 UTC, AwareFoxy commented
> Какой аппрув? Ты вообще его читал? @AwareFoxy 

Все нормально, не вижу ничего говнявого

2024-11-16 11:31 UTC, FireNameFN requested changes

2024-11-16 11:31 UTC, FireNameFN commented on Content.Server/Fluids/EntitySystems/AbsorbentSystem.cs
> +        // Corvax-Footsteps-Start
```suggestion
        // Corvax-Next-Footprints-Start
```

2024-11-16 11:31 UTC, FireNameFN commented on Content.Server/Fluids/EntitySystems/AbsorbentSystem.cs
> +        // Corvax-Footsteps-End
```suggestion
        // Corvax-Next-Footprints-End
```

2024-11-16 11:31 UTC, FireNameFN commented on Content.Server/Fluids/EntitySystems/AbsorbentSystem.cs
> +    // Corvax-Footsteps-Start
```suggestion
    // Corvax-Next-Footprints-Start
```

2024-11-16 11:31 UTC, FireNameFN commented on Content.Server/Fluids/EntitySystems/AbsorbentSystem.cs
> +    // Corvax-Footsteps-End
```suggestion
    // Corvax-Next-Footprints-End
```

2024-11-16 11:31 UTC, FireNameFN commented on Content.Server/_CorvaxNext/Footprints/EntitySystems/FootprintsSystem.cs
Не трогай этот файл.

2024-11-16 11:41 UTC, CaptainSqrBeard commented on Content.Server/_CorvaxNext/Footprints/EntitySystems/FootprintsSystem.cs
почему?

2024-11-16 11:50 UTC, FireNameFN commented
Куда я жмал?

2024-11-16 11:58 UTC, FireNameFN commented
Теперь на тест.

2024-11-16 12:02 UTC, CaptainSqrBeard commented
бессовестный, сидит форспушит в мой же брэнч

2024-11-16 12:14 UTC, CaptainSqrBeard commented
я потестил, у меня работает

2024-11-16 12:19 UTC, FireNameFN approved these changes
Ладно, допустим.

2024-11-16 16:46 UTC, Tornado-Technology submitted a review, later dismissed

2024-11-16 18:03 UTC, CaptainSqrBeard commented on Content.Server/Fluids/EntitySystems/AbsorbentSystem.cs
> +            if (TryComp<MapGridComponent>(gridUid, out var mapGrid))
Проверил на планетарных картах Silly, Terra, а также экспедициях. Везде работает

![f_exp](https://github.com/user-attachments/assets/adf97043-2330-4b4f-9530-644043ee418e)
![f_terra](https://github.com/user-attachments/assets/a486d955-b105-4ce9-a5fe-e4b049e955e5)
![изображение](https://github.com/user-attachments/assets/39c286cd-2774-46b3-b1d7-cd2c04fd9982)

2024-11-17 07:21 UTC, FireNameFN requested changes

2024-11-17 07:21 UTC, FireNameFN commented on Content.Server/Fluids/EntitySystems/AbsorbentSystem.cs
> +    public const float FootprintAbsorptionRange = 0.25f;
```suggestion
    public const float FootprintAbsorptionRange = 0.25f; // Corvax-Next-Footprints
```

2024-11-18 11:54 UTC, FireNameFN approved these changes

2024-11-18 19:27 UTC, AwareFoxy approved these changes

2024-11-18 19:44 UTC, AwareFoxy commented
Тесты проходят, кушать можно.

2024-11-18 19:45 UTC, merged