[Port] Autovote System
space-syndicate/space-station-14-next pull request #62
Opened 2024-11-15 20:04 UTC by PuroSlavKing

## Описание PR

Taken from: https://github.com/Simple-Station/Einstein-Engines/pull/1213

Система автоматических голосований. После конца раунда автоматически запускаются голосования за следующий режим и карту.

## Почему / Баланс

Педалям меньше кнопочек жать

## Ссылка на ветку

## Технические детали

## Медиа

![image](https://github.com/user-attachments/assets/7ad504cb-3070-4cde-a43e-9127d2e2e268)

## Критические изменения

**Список изменений**
:cl: sleepyyapril
- add: Добавлена система автоматических голосований. После конца раунда автоматически запускаются голосования за следующий режим и карту.

2024-11-15 21:30 UTC, FireNameFN commented
На Корваксе, вроде, отключены голосования от игроков за карты.

2024-11-15 21:35 UTC, PuroSlavKing commented
> На Корваксе, вроде, отключены голосования от игроков за карты.

Оно и так выключено, нужно отдельно в конфиге каждого сервера включить

2024-11-16 04:02 UTC, AwareFoxy commented
Пойду у Ксено спрошу

2024-11-16 16:40 UTC, Tornado-Technology approved these changes
Исты сделали довольно локаничный код, есть стилистические приебки, но каждый пишет как хочет

2024-11-18 20:48 UTC, lzk228 commented
БЛЯ НУ НЕ НАДО ЭТО, РАНДОМ КАРТЫ ЭТО ТОП НАМ НЕ НАДО ГОЛОСОВАНИЯ

2024-11-18 22:22 UTC, PuroSlavKing commented
> БЛЯ НУ НЕ НАДО ЭТО, РАНДОМ КАРТЫ ЭТО ТОП НАМ НЕ НАДО ГОЛОСОВАНИЯ

Боится, что голоса за силли айланд уйдут в минус 😈

2024-11-20 19:03 UTC, NotSoDana commented
> Педалям меньше кнопочек жать

Педалям запрещены голосования за карты..
За режим ещё ок, но за карту резко против, ибо начнётся ебаный дроч дельты (опять)

2024-11-20 19:14 UTC, PuroSlavKing commented
> > Педалям меньше кнопочек жать
> 
> Педалям запрещены голосования за карты..
> За режим ещё ок, но за карту резко против, ибо начнётся ебаный дроч дельты (опять)

Кинешь ПР выключающий голосования за карты на твоём сервере

2024-11-20 19:17 UTC, NotSoDana commented
> 
> Кинешь ПР выключающий голосования за карты на твоём сервере

Они и так выключены ВЕЗДЕ и запрещён педалям кодексом. Зачем давать возможность снова пикать каждый раунд дельту, если игроки сами проголосовали за то чтоб ротация была рандомная. Это тупо ломает все усилия на протяжении нескольких месяцев

2024-11-20 19:29 UTC, PuroSlavKing commented
> > 
> > Кинешь ПР выключающий голосования за карты на твоём сервере
> 
> Они и так выключены ВЕЗДЕ и запрещёны педалям кодексом. Зачем давать возможность снова пикать каждый раунд дельту, если игроки сами проголосовали за то чтоб ротация была рандомная. Это тупо ломает все усилия на протяжении нескольких месяцев
> 

Раз выключены, то не включайте, лол, это билд не только для корвакса

2024-11-29 02:53 UTC, Tornado-Technology commented on Content.Shared/_CorvaxNext/NextVars.cs
> +        /// <summary>
ПРОКЛЯТЬЕ ТАБУЛЯЦИИ 440!!!

2024-11-29 02:57 UTC, Tornado-Technology approved these changes
UwU

2024-11-29 03:05 UTC, Tornado-Technology commented
Я откатил изменение МРП конфига, так что как механ, можно спокойно мерджить

2024-11-29 05:15 UTC, AwareFoxy commented
Сделать бы это возможность выключать кнопочкой

2024-11-29 13:09 UTC, FireNameFN requested changes

2024-11-29 13:09 UTC, FireNameFN commented on Content.Shared/_CorvaxNext/NextVars.cs
> +    /// _CorvaxNext Surgery cvars
Лучше оставь.

2024-11-29 13:09 UTC, FireNameFN commented on Content.Shared/_CorvaxNext/NextVars.cs
> +            CVarDef.Create("vote.preset_autovote_enabled", true, CVar.SERVERONLY);
Отступа слишком много, кажется.

2024-11-29 13:09 UTC, FireNameFN commented on Content.Server/_CorvaxNext/AutoVote/AutoVoteSystem.cs
> +        base.Initialize();
Вызов пустого метода.

2024-11-29 13:09 UTC, FireNameFN commented on Content.Server/_CorvaxNext/AutoVote/AutoVoteSystem.cs
> +    public void OnReturnedToLobby(RoundRestartCleanupEvent ev) => CallAutovote();
Ванлайнеры делают только на свойствах.

2024-12-15 04:02 UTC, Tornado-Technology commented on Content.Server/_CorvaxNext/AutoVote/AutoVoteSystem.cs
> +        base.Initialize();
base должен вызывается всегда, считается хорошим тоном

2025-04-10 07:55 UTC, Tornado-Technology commented
Если захочешь доделать - переоткрой.

2025-04-10 07:55 UTC, closed without merging