Еретики
space-syndicate/space-station-14-next pull request #63
Opened 2024-11-16 22:58 UTC by AverageNotDoingAnythingEnjoyer

## Описание PR

В игру добавлены Еретики, основанные на PR'ах https://github.com/Goob-Station/Goob-Station/pull/563 https://github.com/Goob-Station/Goob-Station/pull/601 https://github.com/Goob-Station/Goob-Station/pull/615 https://github.com/Goob-Station/Goob-Station/pull/628 https://github.com/Goob-Station/Goob-Station/pull/723 https://github.com/Goob-Station/Goob-Station/pull/726 https://github.com/Goob-Station/Goob-Station/pull/766 https://github.com/Goob-Station/Goob-Station/pull/795 https://github.com/Goob-Station/Goob-Station/pull/840

Список оставшихся дел:
- [ ] Доперевести локализацию
- [ ] Понять как исправить баг с магазином Еретика (при покупке предметов в ритуальном круге не появляются соответствующие ритуалы)

## Почему / Баланс

"gaming" — Автор оригинального PR'a

## Ссылка на ветку

https://discord.com/channels/919301044784226385/1306351939835133975

## Технические детали

(в процессе написания)
Большая часть нововведений содержится в папках _Goobstation в Content.Server, Content.Shared, Content.Client, Textures и Prototypes.
Также в системы и компоненты Магазина были внесены небольшие правки для корректной работы Антагониста.

## Медиа

(в процессе написания)

## Критические изменения

(в процессе написания)

**Список изменений**

:cl: whateverusername0 (ported by J C Denton)
- add: Забыты, пожраны, выпотрошены. Человечество забыло о древних силах разложения, но завеса Мансуса ослабла. Мы заставим их снова почувствовать страх.
(в процессе написания)

2024-11-17 06:52 UTC, FireNameFN commented
Вообще не понятно, что это из себя представляет. Ни в этом ПР, ни в первом ПРе из ссылок не написано, что именно это такое.

2024-11-18 06:35 UTC, foboscheshir commented
"Забытый, съеденный, выпотрошенный. Человечество забыло о жуткой силе разложения, но завеса Мансуса ослабла. Мы заставим их снова вкусить страх..." :trollface:

2024-11-21 20:26 UTC, xKREKSx commented
> Вообще не понятно, что это из себя представляет. Ни в этом ПР, ни в первом ПРе из ссылок не написано, что именно это такое.

не слышал о еретиках? 
https://tgstation13.org/wiki/Heretic почитай
не всё точ в точ тоже самое, но еретики есть еретики

2024-11-21 22:22 UTC, AverageNotDoingAnythingEnjoyer commented
> кстати, а почему мансус грасп переведён как Хват Обители, разве не Хват ОбителЯ?

Под Mansus подрузамевается измерение мифическое, мир сновидений. Поэтому вроде надо склонять как Обители?

2024-11-23 00:36 UTC, 7-62x54r commented
Резня 👍

2024-11-23 11:09 UTC, whateverusername0 commented
![image](https://github.com/user-attachments/assets/887d10e2-9a01-4f4f-88e9-e0365d75fbf9)
девочки я плачу

2024-11-27 07:16 UTC, whateverusername0 commented
https://github.com/Goob-Station/Goob-Station/pull/945 @AverageNotDoingAnythingEnjoyer зацени

2024-11-27 08:14 UTC, AverageNotDoingAnythingEnjoyer commented
> [Goob-Station/Goob-Station#945](https://github.com/Goob-Station/Goob-Station/pull/945) @AverageNotDoingAnythingEnjoyer зацени

Опаньки, имба, это нам надо. Добавлю как конфликты пофикшу

2024-11-29 07:47 UTC, whateverusername0 requested changes
Оценил твой перевод

2024-11-29 07:47 UTC, whateverusername0 commented on Resources/Locale/ru-RU/_Goobstation/Heretic/abilities/heretic.ftl
> +heretic-ability-fail-magicitem = Этот ритуал требует сосредоточения!
Не ритуал а способность
Напиши "Нужен фокус" и всё :godmode:

2024-11-29 07:47 UTC, whateverusername0 commented on Resources/Locale/ru-RU/_Goobstation/Heretic/game-ticking/game-presets/preset-heretic.ftl
> +ghostrole-stalker-desc = Помогите своему призывателю вознестись. Ступайте и лишите станцию света.
Тут лучше будет написать "Ходите сквозь стены и лишайте станцию света"

2024-11-29 07:47 UTC, whateverusername0 commented on Resources/Locale/ru-RU/_Goobstation/Heretic/heretic/misc.ftl
> +heretic-influence-start = Накапливаем влияние...
Тут лучше написать "Поглощаем разлом"

2024-11-29 07:47 UTC, whateverusername0 commented on Resources/Locale/ru-RU/_Goobstation/Heretic/heretic/rituals.ftl
> +heretic-ritual-basic-focus = Янтарное Сосредоточение
Вообще лучше переименовать все сосредоточения в Фокусы
Янтарный Фокус имхо звучит гораздо лучше и проще понимается

2024-11-29 07:47 UTC, whateverusername0 commented on Resources/Locale/ru-RU/_Goobstation/Heretic/heretic/rituals.ftl
> +heretic-ritual-basic-heart = Проклятое Сердце
Беспокойное Сердцебиение :godmode:

2024-11-29 07:47 UTC, whateverusername0 commented on Resources/Locale/ru-RU/_Goobstation/Heretic/objectives/heretic.ftl
> +objective-condition-sacrifice-title = Принесите в жертву как минимум {$count} членов экипажа.
>Принесите в жертву как минимум 1 членов экипажа.
>Принесите в жерткву как миниму 2 члена командования.

Если попадутся такие приколы будет не очень :trollface:

2024-11-29 07:47 UTC, whateverusername0 commented on Resources/Locale/ru-RU/_Goobstation/Heretic/roles/heretic.ftl
> +roles-antag-heretic-description = Находите разломы, убедитесь, что они все собраны. Приносите людей в жертву и обретите могущество (или умрите).
"Поглощайте разломы, приносите людей в жертву. Станьте всемогущим или умрите пытаясь"

2024-11-29 07:47 UTC, whateverusername0 commented on Resources/Locale/ru-RU/_Goobstation/Heretic/store/heretic/heretic-catalog-ash.ftl
> +    Ни один огонь не был достаточно горячим, чтобы разжечь ИХ. Ни один огонь не был достаточно ярким, чтобы спасти ИХ. Ни один огонь не вечен.
Почему ИХ с большой буквы?

2024-11-29 07:47 UTC, whateverusername0 commented on Resources/Locale/ru-RU/_Goobstation/Heretic/store/heretic/heretic-catalog-ash.ftl
> +    If any victims afflicted are in critical condition, they will instantly die.
Почему флавор переведён а сами описания абилок нет? :trollface:

2024-11-29 07:47 UTC, whateverusername0 commented on Resources/Locale/ru-RU/_Goobstation/Heretic/store/heretic/heretic-catalog-flesh.ftl
> +    По завершению, вы получите способность отринуть свою человечность и стать Лордом Ночи, всемогущим существом.
Перевод не точен. После 5 апдейта я сделал так чтобы еретик при вознесении сразу становился meatball man'ом без возможности вернуться назад

2024-11-29 07:47 UTC, whateverusername0 commented on Resources/Locale/ru-RU/_Goobstation/Heretic/store/heretic/heretic-catalog-rust.ftl
> +    Rust also spreads from the ritual's rune, covering the station slowly.
Раста не будет...

2024-12-04 08:58 UTC, Seven2280 commented
@AverageNotDoingAnythingEnjoyer 
Можешь сказать как не черрипикать отдельно каждый коммит, а сразу ПР? Я возможно плохо искал и давал плохие промты, но ни в чате гпт об этом нет, ни в интернете.

2024-12-04 11:15 UTC, AverageNotDoingAnythingEnjoyer commented
> @AverageNotDoingAnythingEnjoyer Можешь сказать как не черрипикать отдельно каждый коммит, а сразу ПР? Я возможно плохо искал и давал плохие промты, но ни в чате гпт об этом нет, ни в интернете.

Просто прописываешь cherry-pick комита, который смёрджил все комиты с пра в ветку

2024-12-04 12:58 UTC, AwareFoxy commented
Я тебя люблю.

2024-12-06 03:28 UTC, AwareFoxy commented
@AverageNotDoingAnythingEnjoyer привет, напиши мне в лс пожалуйста - @awarefoxy в дискорд.

2024-12-27 15:06 UTC, whateverusername0 commented on Resources/Locale/ru-RU/_CorvaxNext/heretic/heretic/ascensions.ftl
> +    Дозорный - пал
еретик возносится и начинаеи рэп читать вместо нормального монолога
стена текста не одобряю

2024-12-27 15:11 UTC, whateverusername0 commented on Resources/Locale/ru-RU/_CorvaxNext/heretic/objectives/heretic.ftl
> +objective-condition-description-ascend = Я обязан сделать это во имя Вознесения!
лучше верни старый objective-condition-description-ascend
звучит так будто еретик делает это для какого-то дяди по ту сторону, а не для того чтобы стать богом

2024-12-27 15:13 UTC, whateverusername0 commented on Resources/Locale/ru-RU/_CorvaxNext/heretic/store/heretic/heretic-catalog-blade.ftl
> +knowledge-path-blade-s2-name = Хватка Лезвия
ты потерял `knowledge-path-blade-s1-name` и `s1-desc`

2024-12-27 15:14 UTC, whateverusername0 commented on Resources/Locale/ru-RU/_CorvaxNext/heretic/store/heretic/heretic-catalog-blade.ftl
> +    Трансмутируйте 3 трупа, чтобы принять Возвыситься.
у вас уже есть ньюмед и путь клинка давно мною доделан.
у меня там сделано три обезглавленных трупа. тут так же надо

2024-12-27 15:16 UTC, whateverusername0 commented on Resources/Locale/ru-RU/_CorvaxNext/heretic/store/heretic/heretic-catalog-flesh.ftl
> +    Дарует вам заклинание "Переплетение Плоти". Оно позволяет вам вытаскивать органы из жертв
спелл хирургии такого не делает.
он достаёт рандомный орган из не еретика
и лечит тебя и гулей, если навестись

2024-12-27 15:18 UTC, whateverusername0 requested changes
в переводе опять тонна флавора большинство которого читаться не будет, поверь
надо сделать поменьше загадочности и быть поближе к делу
хорошим примером как делать не надо являются стихи не только в текстах вознесении но и в **описаниях в магазине** (??? зачем и почему)
ещё добавил комментариев где надо

2024-12-27 15:19 UTC, whateverusername0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/_corvaxnext/heretic/entities/objects/weapons/melee/heretic_blades.ftl
> +ent-HereticBladeBase = элдрический клинок
древний клинок.

2024-12-27 15:20 UTC, whateverusername0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/_corvaxnext/heretic/actions/heretic/path_flesh.ftl
> +action-heretic-flesh-surgery-desc = Удалите случайный орган жертвы.
забыл про хил тиммейтов добавить

2024-12-27 15:21 UTC, whateverusername0 commented
уже лучше перевод выглядит

2025-02-20 12:22 UTC, Golubgik commented
Кто-то жив?

2025-04-24 20:37 UTC, closed without merging

2025-04-24 20:37 UTC, AverageNotDoingAnythingEnjoyer commented
Некст уже и так портировал, так что...победа?

2025-04-24 21:02 UTC, lzk228 commented
это поражение