Хирургия (попытка 2)
space-syndicate/space-station-14-next pull request #65
Opened 2024-11-17 18:06 UTC by TokenStyle

## Описание PR
> Мифическая система хирургии. О ней шепчут приглушённо в уголках *"Хирургия через неделю"*, она существует уже два года. Если прислушаться очень внимательно, можно услышать звук, как проваливаются все интеграционные тесты.

Полностью переделана система ранений, добавлена хирургия, сложные манипуляции с частями тела и органами, а также понятное отображение всего процесса для игроков.

Взято с [Shitmed PR](https://github.com/Simple-Station/Einstein-Engines/pull/1159), спасибо большое @gluesniffler !
Спасибо большое [Shitmed Port PR](https://github.com/Rxup/space-station-14/pull/868) @Roudenn !

## Почему / Баланс
*"Хирургия через неделю"*

## Технические детали
> A lot of things will break, expect a lot of merge conflicts every time anything BodySystem is touched now.

Привет хирургия и привет апстрим конфликты!

Все известные баги были исправлены и добавлено кучу новых механик 2024-11-17:
- [x] Лаги, что дают около 20-30% нагрузки... И со временем становится хуже, похоже на утечку памяти.
- [x] Любой нестандартный урон игроку будет попадать именно в левую ногу (взрывы или противники, которые не целятся в куклу).
- [x] Нет возможности увидеть, какие конечности повреждены конкретно со стороны (было бы хорошо иметь отображение куклы в анализаторе здоровья).
- [x] Урон кукле и урон сущности не синхронизированы должным образом (исцеление происходит только при прицеливании в повреждённую конечность, и если есть повреждённая конечность, а общий урон равен 0, медикаменты будут тратиться бесконечно впустую). (Вероятно, лечение должно автоматически нацеливаться на наиболее повреждённую конечность).
- [x] ~~Нет простого способа увидеть, что именно нарушено внутри тела пациента (отсутствующие органы, повреждённые кости и т. д.).~~ Сломанные органы не повлияют на работоспособность/эффективность.
- [x] Дебаг Лечение не лечит органы
- [x] Можно оперировать самого себя (что-то чего обычно быть не должно, по крайней мере без подготовки)
- [x] Во время удаления (или пришивания в определённых случаях) конечностей, разрезы автоматически закрываются, даже не смотря на то что они не были ни кем закрыты.
- [x] Вы не можете достать предмет, который вы вставили в чье-то тело (например, ядерный диск, который вы вставили в капитана, вы не можете достать его обратно).

Ссылки на источники: https://github.com/Rxup/space-station-14/issues/873

## Медиа

https://github.com/user-attachments/assets/91187ecd-9294-4d26-9671-0e9cc5f8c490

[![Surgery video](https://img.youtube.com/vi/UhxS5b3LC-A/0.jpg)](https://www.youtube.com/watch?v=UhxS5b3LC-A)

## Требования

- [x] Я прочитал(а) и следую [Рекомендациям по оформлению Pull Request и Changelog](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] Я добавил(а) медиафайлы к этому PR или он не требует демонстрации в игре.

## Критические изменения
Точно ничего хорошего.

**Список изменений**

:cl:
- add: Хирургия теперь есть для всех живых существ!
- add: Теперь есть полноценные органы, конечности, ранения!
- add: Теперь ранения наносятся на определённые органы!
- add: Теперь врачи, хирурги, и главный врач быстро проводят хирургические операции!
- add: Отсутствие сердца, мозга теперь убивает персонажа!
- add: Теперь есть Медицинский биофабрикатор, который печатает органы, конечности!

2024-11-17 18:25 UTC, AwareFoxy commented
Я тебя люблю.
Тесты кста не проходят, возможно ты туда просто что-то не добавил.

2024-11-17 18:37 UTC, TokenStyle commented
> Resources/Textures/Structures/Machines/limbgrower.rsi: meta.json: [$.license] 'GNU AGPL v3' is not one of ['CC-BY-3.0', 'CC-BY-4.0', 'CC-BY-SA-3.0', 'CC-BY-SA-4.0', 'CC-BY-NC-3.0', 'CC-BY-NC-4.0', 'CC-BY-NC-SA-3.0', 'CC-BY-NC-SA-4.0', 'CC0-1.0']

Тесты валятся, limbgrower.rsi не лицензирован, буду прокидывать лицензию

2024-11-17 18:38 UTC, TokenStyle commented
> Exception whilst loading prototypes from /Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml:

chief_medical_officer с ним кринж, тоже пофикшу

2024-11-17 18:48 UTC, AwareFoxy commented
@TokenStyle ты как систему боли делал?(мне щас гиперлень смотреть код)
Она же в муд систем от ЕЕ была, или ты её тоже портировал

2024-11-17 18:54 UTC, TokenStyle commented
@AwareFoxy Нету системы боли, нет системы Mood. Боль = Mood/Morale система https://github.com/Rxup/space-station-14/pull/881 отдельным ПРом, т.к имхо система боли/настроения это не зависящий от хирургии механ, или если всё точно ок, могу залить всё вместе. Хирургия + лежание + система боли/настроения/морали

2024-11-17 19:01 UTC, Roudenn commented
Эта версия хирургии сейчас тестится на разных сборках, в ней все ещё могут быть непредсказуемые баги или проблемы с балансом. Можно сказать это бета-тест, и все равно конкретно на Backmen из-за различного баланса оружия цифры могут быть слишком неподходящими для ванильных сборок.

2024-11-17 19:02 UTC, Roudenn commented
> AwareFoxy Нету системы боли, нет системы Mood. Боль = Mood/Morale система [Rxup/space-station-14#881](https://github.com/Rxup/space-station-14/pull/881) отдельным ПРом, т.к имхо система боли/настроения это не зависящий от хирургии механ, или если всё точно ок, могу залить всё вместе. Хирургия + лежание + система боли/настроения/морали

Система морали на Backmen сейчас слишком в сыром виде, мы скоро допортируем и дополним версию с EE чтобы потом забалансировать и протестировать в полной мере

2024-11-18 06:46 UTC, YuiFann commented
гол

2024-11-21 15:19 UTC, trest100 requested changes
Замечания на данный момент:
1.Все файлы перенести из папки BackMen в папку Next'a 
2. Сменить неймспейсы 
3. Сменить коментарии с BackMen EDIT на NEXT EDIT

2024-11-22 13:42 UTC, AwareFoxy approved these changes
токен я тебя люблю

2024-11-22 14:31 UTC, FireNameFN requested changes

2024-11-22 14:31 UTC, FireNameFN commented on Content.Client/_CorvaxNext/Body/BodySystem.cs
> +namespace Content.Client.Body.Systems;
```suggestion
namespace Content.Client._CorvaxNext.Body.Systems;
```

2024-11-22 14:32 UTC, FireNameFN commented
Гитхаб пипец лагает, так что ищите сами, где ещё там неймпейсы не проставлены.

2024-11-22 21:20 UTC, AwareFoxy commented
Это один маленький шаг для разработчика и огромный шаг для вс- нам пизда от визденов.

2024-11-22 21:20 UTC, merged

2024-11-22 23:46 UTC, tripsov commented
Невозможно...