[Port] Хирургия оперирование обезьян и кобольдов
space-syndicate/space-station-14-next pull request #77
Opened 2024-11-24 00:22 UTC by TokenStyle

## Описание PR
Теперь макаки и кобольды оперируются. Работает хорошо, даже спрайты удаляются, например голову отрубил, и теперь кобольд не имеет спрайта головы и т.д.

## Почему / Баланс
Обезьян и кобольдов оперировать весело, а пересаживать конечности обезьян/кобольдов это весело.

## Ссылка на ветку

## Технические детали
Ну вроде работает.

## Медиа

## Критические изменения

**Список изменений**

:cl:
- add: Теперь для хирургии доступны обезьяны и кобольды с полноценными конечностями и органами!

2024-11-24 00:23 UTC, TokenStyle commented
Это нужно ещё на CorvaxNext подпаку перенести и все backmen заменить на _CorvaxNext но я устал

2024-11-25 00:55 UTC, AwareFoxy commented
@Morb0 @ksen0morph для вас

2024-11-25 09:19 UTC, TokenStyle commented
Не мёржим пока-что, я сразу все фиксы сюда портирую, за сёдня планирую

2024-11-25 10:34 UTC, TokenStyle commented
Бля хештеги с ПРами не те подтянулись... ну и похер

2024-11-25 22:16 UTC, AwareFoxy commented
@TokenStyle импланты будешь портировать?

2024-11-26 09:04 UTC, TokenStyle commented
> @TokenStyle импланты будешь портировать?

Да :gigachad:

2024-11-26 22:47 UTC, FireNameFN requested changes
Не буду дальше смотреть. Комменты везде должны быть:
// Corvax-Next-Surgery
либо
// Corvax-Next-Surgery-Start
// Corvax-Next-Surgery-End

2024-11-26 22:47 UTC, FireNameFN commented on Content.Client/Hands/Systems/HandsSystem.cs
> +using Content.Shared._CorvaxNext.Surgery.Body.Events;
Он используется?

2024-11-26 22:47 UTC, FireNameFN commented on Content.Client/Smoking/MatchstickSystem.cs
Замени эти комментарии на один, который будет на стройке с классом.
// Corvax-Next-Surgery

2024-11-26 22:47 UTC, FireNameFN commented on Content.Server/Body/Systems/BodySystem.cs
Comments.

2024-11-26 22:47 UTC, FireNameFN commented on Content.Server/Body/Systems/BrainSystem.cs
Исправить комментарии.

2024-11-26 22:47 UTC, FireNameFN commented on Content.Server/Body/Systems/RespiratorSystem.cs
> +            if (!_mobState.IsIncapacitated(uid) && !HasComp<DebrainedComponent>(uid)) // _CorvaxNext Change - Cannot breathe in crit or when no brain.
Снова говно коммент.

2024-11-26 22:50 UTC, TokenStyle commented on Content.Client/Hands/Systems/HandsSystem.cs
> +using Content.Shared._CorvaxNext.Surgery.Body.Events;
Да, без него будет ошибка. Я уже пробовал убирать не компилиться

2024-11-26 22:56 UTC, TokenStyle commented
@FireNameFN Поменял комменатрии. Точно на `// Corvax-Next-Surgery` сделать? Могу сделать структуру как `// CorvaxNext: surgery etc etc` т.к бакмен использует двоеточия `// backment: surgery` и гит сможет такие изменения отлавливать и подтягивать без Мерж конфликта.

2024-11-26 23:33 UTC, TokenStyle commented
@AwareFoxy Да, сейчас все комменты выглядят как `// CorvaxNext: surgery bla bla bla`

2024-11-26 23:36 UTC, merged