Add playable cards
space-syndicate/space-station-14-next pull request #79
Opened 2024-11-24 18:46 UTC by Vonsant

## Описание PR

Добавляет колоду игральных карт, вместе с механикой для её использования. Карты можно переворачивать, перемешивать, раскладывать и складывать в колоды. Их можно купить в автомате безобидных развлечений.

## Почему / Баланс

Фан.

## Технические детали

Портирована система игральных карт с https://github.com/rbertoche/space-station-14/pull/104
Так же портирована доработка с https://github.com/new-frontiers-14/frontier-station-14/pull/2038

## Медиа

https://github.com/user-attachments/assets/09a7a3f6-b2d8-44d7-8642-962bd9d8c9fc

**Список изменений**

:cl:
- add: Добавлены игральные карты. Их можно приобрести в автомате безобидных развлечений.

2024-11-24 20:01 UTC, AwareFoxy commented
testi

2024-11-24 20:01 UTC, Vonsant commented
> testi

Это проблема на ПРа, забей.

2024-11-24 20:02 UTC, Vonsant commented
Не мержи, а проверь код.

2024-11-24 20:12 UTC, FireNameFN requested changes
В карты подмешалась какая-то броня.

2024-11-24 20:12 UTC, FireNameFN commented on Resources/Prototypes/Corvax/Entities/Clothing/OuterClothing/armor.yml
Что это?

2024-11-24 20:12 UTC, FireNameFN commented on Resources/Textures/Corvax/Clothing/OuterClothing/Armor/uic_armor_light_vest.rsi/equipped-OUTERCLOTHING.png
И что это вместе с другими файлами?

2024-11-24 20:20 UTC, Vonsant commented
> В карты подмешалась какая-то броня.

Забыла почистить перед ПРом, уэ.

2024-11-25 11:51 UTC, lzk228 reviewed
это максимум что я могу тут ревьювнуть
ещё могу к форматированию придраться разве что

2024-11-25 11:51 UTC, lzk228 commented on Content.Client/_CorvaxNext/Cards/Card/CardSystem.cs
> +/// This handles...
чё хендлит

2024-11-25 11:51 UTC, lzk228 commented on Content.Client/_CorvaxNext/Cards/CardSpriteSystem.cs
> +/// This handles...
чё

2024-11-25 11:51 UTC, lzk228 commented on Content.Client/_CorvaxNext/Cards/Deck/CardDeckSystem.cs
> +/// This handles...
плюс тут

2024-11-25 11:51 UTC, lzk228 commented on Content.Client/_CorvaxNext/Cards/Hand/CardHandSystem.cs
> +/// This handles...
и так далее

2024-11-25 20:23 UTC, AwareFoxy submitted a review, later dismissed
процедурная генерация карт исходя из колоды, просто ахуенно

2024-11-25 22:03 UTC, FireNameFN submitted a review, later dismissed

2024-11-25 22:03 UTC, FireNameFN commented on Content.Shared/_CorvaxNext/Cards/Deck/CardDeckSystem.cs
> +    public readonly EntProtoId CardDeckBaseName = "CardDeckBase";
```suggestion

    public static readonly EntProtoId CardDeckBaseName = "CardDeckBase";
```

2024-11-25 22:03 UTC, FireNameFN commented on Resources/Audio/_CorvaxNext/Effects/Cards/attributions.yml
> +﻿- files: [  "cardFan1.ogg", "cardFan2.ogg", "cardOpenPackage1.ogg", "cardOpenPackage2.ogg", "cardPlace1.ogg", "cardPlace2.ogg", "cardPlace3.ogg", "cardPlace4.ogg", "cardShove1.ogg", "cardShove2.ogg"
Преобразуй в полноценный список, а не однострочный.

2024-11-25 22:03 UTC, FireNameFN commented on runclient - Release.bat
Такое пока не надо.

2024-11-25 22:03 UTC, FireNameFN commented on runserver - Release.bat
Такое пока не надо.

2024-11-25 23:40 UTC, Vonsant commented
Тесты норм, так и должно быть.

2024-11-26 00:11 UTC, merged

2024-12-05 16:58 UTC, Day-OS commented
glad you guys liked it!

(just to mention, we actually speak portuguese, not english... but well that's that)

Спасибо!