[Port] Advanced Prying
space-syndicate/space-station-14-next pull request #82
Opened 2024-11-25 12:13 UTC by PuroSlavKing

## Описание PR

Taken from: https://github.com/WWhiteDreamProject/wwdpublic/pull/31
Мгновенное открытие обесточенных шлюзов (Повышение динамики + SS13 Reference) инструментами и повышение полезности топора.

## Почему / Баланс

Особо не повлияет.

## Ссылка на ветку

## Технические детали

## Медиа

## Критические изменения

**Список изменений**

:cl: Warete
- tweak: Изменено открытие обесточенных шлюзов, теперь при помощи инструментов они открываются и закрываются мгновенно.
- tweak: Добавлена возможность срывать тайлы покрытия, при помощи топора.

2024-11-26 09:40 UTC, CaptainSqrBeard commented
# Тестирование

- Плитка снимается ломом моментально. Это офигенно, когда что-то строишь и тебе надо поменять пол. Хотя и внешний вид станции теперь тоже легко гриферится. За пол минуты можно сделать то, что я сделал на скриншоте, а то и быстрее.
- Покрытие (тайлы без плитки) тоже снимается мгновенно, но только при помощи топора. Вот это уже не очень хорошо. Гриферить атмосферу на станции ещё никогда не было так просто.
- Челюсти жизни не снимают плитку моментально, вероятно это баг.

![изображение](https://github.com/user-attachments/assets/21d92eff-fb5a-460a-842b-532c868132b2)

2024-11-26 18:09 UTC, FireNameFN requested changes
И так везде

2024-11-26 18:09 UTC, FireNameFN commented on Content.IntegrationTests/Tests/DoAfter/DoAfterCancellationTests.cs
> +        // CORVAX-NEXT START
```suggestion
        // Corvax-Next-AdvancedPrying-Start
```

2024-11-26 18:15 UTC, CaptainSqrBeard commented
> Челюсти жизни моментально открываются запитанные/заблокированные шлюзы. Синдикатовские.
> Хорошая замена емагу. Ещё и стоит 2тк

Нету такого. Запитанные двери всё ещё открываются с длинной задержкой.

2024-11-27 06:38 UTC, PuroSlavKing commented
> > Нету такого. Запитанные двери всё ещё открываются с длинной задержкой. 
> 
> Все да. Но почему-то синдикатовские так не думают.

Потому-что у них скорость вскрытия на 1.5 больше чем у обычных, буквально недавно подняли эту тему на бекмене, тебе ли не знать

2025-05-18 14:18 UTC, closed without merging