[Fix] Починил названия и описания блюд.
space-syndicate/space-station-14-next pull request #87
Opened 2024-11-26 21:22 UTC by AwareFoxy

## Описание PR
Починил названия и описания блюд.

## Почему / Баланс
Потому что это пиздец

**Список изменений**
:cl:
- fix: Были исправлены описания и названия блюд!

2024-11-26 21:28 UTC, Vonsant requested changes
Айдишники в прототипах блюд поменял, а в спавнерах и рецептах не поменял. Дорабатывай.

2024-11-26 21:41 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/_corvaxnext/entities/objects/consumble/food/produce.ftl
> +    .desc = У меня созрел вопрос...
я бы сделал "Созрел вопрос..." как и было в меме

2024-11-26 21:41 UTC, lzk228 submitted a review, later dismissed

2024-11-26 22:23 UTC, FireNameFN requested changes

2024-11-26 22:23 UTC, FireNameFN commented on Resources/Prototypes/Entities/Markers/Spawners/Random/Food_Drinks/food_meal.yml
> +      # Corvax-Next-Food-End
End?

2024-11-26 22:23 UTC, FireNameFN commented on Resources/Prototypes/_CorvaxNext/Recipes/Cooking/meal_recipes.yml
>    id: RecipeOkroshkasoup
```suggestion
  id: RecipeOkroshkaSoup
```

Может так сделать всем рецептам?

2024-11-26 22:32 UTC, AwareFoxy commented on Resources/Prototypes/Entities/Markers/Spawners/Random/Food_Drinks/food_meal.yml
> +      # Corvax-Next-Food-End
```suggestion
      # Corvax-Next-Food-Start
```

2024-11-27 14:58 UTC, Vonsant commented on Resources/Prototypes/Entities/Markers/Spawners/Random/Food_Drinks/food_meal.yml
Переделывай везде айди под общий стандарт блюд в СС14.

FoodBearSoup = FoodSoupBear
FoodOlivier = FoodSaladOlivier
FoodSolankaSoup = FoodSoupSolanka

И так далее.

2024-12-18 09:50 UTC, closed without merging