return machine upgrade system
space-syndicate/space-station-14-next pull request #9
Opened 2024-10-25 16:18 UTC by KillanGenifer

Возвращает систему улучшения машин, технологию, открывающую компоненты и РПЗД.

Основная часть кода взята с фронтира. 
За корректную работу системы замены компонентов вручную и РПЗД не ручаюсь, так как не осилил код. Остальное, в виде ивентов обработки компонентов машины после замены запчастей была осмотрена и переделана индивидуально под нашу сборку. 

Сильно лезть в компоненты машин не стал, дабы по минимум отредактировать существующий код. Все коэффиценты, параметры машин при внесении новых запчастей меняются только через хардкод, вырезано в связи с излишним вмешательством.

Если PR будет мёржнут, то докину дополнительные улучшения для новых машин, по типу упаковщика, плиточника, карабельных пушек и т.п.

![goool](https://github.com/user-attachments/assets/52799104-77df-459f-9e0d-7df2e9bf8fc7)

2024-10-25 16:26 UTC, lzk228 commented
а есть кнопка unaprove?

2024-10-26 02:23 UTC, KillanGenifer commented
> а есть кнопка unaprove?

Какая? Где?

2024-10-30 16:00 UTC, AwareFoxy commented
Систему улучшений убрали не просто так.
https://github.com/space-wizards/space-station-14/issues/21055

2024-10-30 23:13 UTC, lzk228 requested changes
кажется ты забыл заполнить часть "почему/баланс" в описании твоего пул реквеста, зпаолни пж

2024-10-30 23:14 UTC, AwareFoxy requested changes
В ПРе ни слова о том, почему вернуть эту механику - хорошая идея.

2024-10-31 01:37 UTC, KillanGenifer commented
В целом позиция оффов мне ясна, тогда фиг с ним.

2024-10-31 01:37 UTC, closed without merging