Spacelaw Change Rule
space-syndicate/space-station-14-next pull request #97
Opened 2024-11-29 23:20 UTC by AwareFoxy

Автор сия творения  - @chavonadelal
## Описание PR
Теперь может выпасть _**ОЧЕНЬ РЕДКИЙ**_ ивент на смену корп закона xdd:
## Почему / Баланс
SS13 content
## Ссылка на ветку

## Технические детали
@Tornado-Technology удачи

## Медиа

## Критические изменения

**Список изменений**
Для чейнджлогера - в качестве автора укажи to4no_fix в ДС
:cl:
- add: Добавлен очень редкий ивент с возможностью смены корпоративных законов!

2024-11-29 23:57 UTC, AwareFoxy commented
> это уже можно тестировать?

там нечего тестировать

2024-11-30 00:03 UTC, lzk228 requested changes
в описании ПРа опиши как собственно происходит этот ивент либо добавь медиа

2024-11-30 06:34 UTC, CaptainSqrBeard commented
> > это уже можно тестировать?
> 
> там нечего тестировать

ЛОЖЬ

2024-11-30 07:07 UTC, Vonsant requested changes
Лрп бред сивой кобылы под метамфетамином. Для мрп большая часть "законов" не подходит. Либо переписать в более серьезном виде, либо принято не будет.

2024-11-30 07:07 UTC, Vonsant commented on Resources/Locale/ru-RU/_CorvaxNext/station-events/events/space-law-change.ftl
> +station-event-space-law-change-essence-23 = неисполнение приветствия "Привет, товарищи" при входе в Бриг
Лрп бред.

2024-11-30 07:07 UTC, Vonsant commented on Resources/Locale/ru-RU/_CorvaxNext/station-events/events/space-law-change.ftl
> +station-event-space-law-change-essence-25 = отказ участвовать в поедании любого блюда с заявленным шеф-поваром "секретным NanoTrasen-ингредиентом"
Лрп бред.

2024-11-30 07:07 UTC, Vonsant commented on Resources/Locale/ru-RU/_CorvaxNext/station-events/events/space-law-change.ftl
> +station-event-space-law-change-essence-29 = лечение при помощи лекарственных средств
Лрп бред

2024-11-30 07:07 UTC, Vonsant commented on Resources/Locale/ru-RU/_CorvaxNext/station-events/events/space-law-change.ftl
> +station-event-space-law-change-essence-14 = не ношение сотрудниками отдела Службы безопаности униформы клоуна
Лрп бред.

2024-11-30 07:07 UTC, Vonsant commented on Resources/Locale/ru-RU/_CorvaxNext/station-events/events/space-law-change.ftl
> +station-event-space-law-change-essence-11 = смерть
Бред.

2024-11-30 07:07 UTC, Vonsant commented on Resources/Locale/ru-RU/_CorvaxNext/station-events/events/space-law-change.ftl
> +station-event-space-law-change-essence-12 = сон
Бред.

2024-11-30 07:07 UTC, Vonsant commented on Resources/Locale/ru-RU/_CorvaxNext/station-events/events/space-law-change.ftl
> +station-event-space-law-change-essence-13 = безработица
Бред.

2024-11-30 07:07 UTC, Vonsant commented on Resources/Locale/ru-RU/_CorvaxNext/station-events/events/space-law-change.ftl
> +station-event-space-law-change-essence-15 = обувь
Бред.

2024-11-30 07:07 UTC, Vonsant commented on Resources/Locale/ru-RU/_CorvaxNext/station-events/events/space-law-change.ftl
> +station-event-space-law-change-essence-17 = общение не шепотом вне каналов связи
Бред.

2024-11-30 07:07 UTC, Vonsant commented on Resources/Locale/ru-RU/_CorvaxNext/station-events/events/space-law-change.ftl
> +station-event-space-law-change-essence-18 = попытки убедить Капитана станции в существовании мировых заговоров
Бред.

2024-11-30 07:07 UTC, Vonsant commented on Resources/Locale/ru-RU/_CorvaxNext/station-events/events/space-law-change.ftl
> +station-event-space-law-change-essence-20 = общение с ИИ без предварительного соблюдения ритуала "Трижды назови свои законы"
Бред

2024-11-30 07:07 UTC, Vonsant commented on Resources/Locale/ru-RU/_CorvaxNext/station-events/events/space-law-change.ftl
> +station-event-space-law-change-essence-21 = попытки объяснить Капитану станции, как работает станция
Бред.

2024-11-30 07:07 UTC, Vonsant commented on Resources/Locale/ru-RU/_CorvaxNext/station-events/events/space-law-change.ftl
> +station-event-space-law-change-essence-30 = использование оглушающего оружия
Бред.

2024-11-30 07:07 UTC, Vonsant commented on Resources/Locale/ru-RU/_CorvaxNext/station-events/events/space-law-change.ftl
> +station-event-space-law-change-essence-10 = неисполнение главой отдела личного приветствия каждого члена экипажа, посещающего его отдел
Бред.

2024-11-30 07:07 UTC, Vonsant commented on Resources/Locale/ru-RU/_CorvaxNext/station-events/events/space-law-change.ftl
> +station-event-space-law-change-essence-8 = деятельность руководителей отделов, которые не уделяют должного внимания патриотическому воспитанию своих сотрудников во славу NanoTrasen
Бред.

2024-11-30 07:07 UTC, Vonsant commented on Resources/Locale/ru-RU/_CorvaxNext/station-events/events/space-law-change.ftl
> +station-event-space-law-change-essence-9 = не ношение головного убора
Бред.

2024-11-30 07:18 UTC, Vonsant commented
Если делаете лрп контент, то для него нужен отдельный цварник, чтобы можно было включать его в серверных настройках. Но по умолчанию должно быть выключено.

Условно rp_lrp = false.

Подавляющее число серверов корвакса позиционируется как мрп, где подобные шутки хуютки с пресмыканием перед клоуном будут восприняты в штыки.

2024-11-30 09:47 UTC, chavonadelal requested changes
Убрать варианты, связанные с оружием, лекарствами и про танцевание с клоуном, потому что от них, возможно, действительно могут быть проблемы. Варианты связанные с оружием и лекарствами вообще не мои, хех. Остальные варианты забавные, с учетом того, что ивент может выпасть всего один раз за раунд с небольшим шансом. Добавьте веселья игрокам, работки им и так хватает. Фокси опередил меня же и зачем-то черепикнул мою ветку в форке 🤔  , так бы сам поправил

2024-11-30 10:04 UTC, CaptainSqrBeard commented
> Лрп бред сивой кобылы под метамфетамином. Для мрп большая часть "законов" не подходит. Либо переписать в более серьезном виде, либо принято не будет.

Помоему вся суть этого ивента в бредовых 1984 законах.

К тому-же я не очень понимаю по какому критерию ты отбираешь ЛРПшные законы, которые бы мешали на МРП. Но этот вопрос я лучше оставлю тому, кто понимает как играются МРП сервера.

2024-11-30 10:08 UTC, CaptainSqrBeard commented on Resources/Locale/ru-RU/_CorvaxNext/station-events/events/space-law-change.ftl
> +station-event-space-law-change-essence-20 = общение с ИИ без предварительного соблюдения ритуала "Трижды назови свои законы"
Такой закон про ИИ приведёт к спаму в чате, что не очень хорошо и наверняка даже является нарушением правил.

2024-12-01 12:09 UTC, Vonsant commented
@AwareFoxy старший модератор провел обсуждение с модераторами серверов и было принято решение, что данный ивент допустим только на сервере Мейн. Так что цварник делать все таки придется.

2024-12-01 12:10 UTC, AwareFoxy commented
> @AwareFoxy старший модератор провел обсуждение с модераторами серверов и было принято решение, что данный ивент допустим только на сервере Мейн. Так что цварник делать все таки придется.

я это в пуссицвар впишу тхен, ок?

2024-12-01 12:11 UTC, Vonsant commented
> я это в пуссицвар впишу тхен, ок?

idk, главное чтобы в будущем этот цварник можно было универсально использовать под разные фичи. В идеале я бы сделала три отдельных фича тоггла под каждый уровень сервера,у словно "мрп-" "мрп" "мрп+", чтобы потом можно было распределять фичи по серверам, а не все сервера единообразными делать.

2024-12-01 12:13 UTC, chavonadelal commented
> @AwareFoxy старший модератор провел обсуждение с модераторами серверов и было принято решение, что данный ивент допустим только на сервере Мейн. Так что цварник делать все таки придется.

Вот это вы скучные

2024-12-01 12:13 UTC, chavonadelal commented
@AwareFoxy раз это для лрп, то верни" ЛРП Бред" законы

2024-12-01 12:14 UTC, Vonsant commented
> @AwareFoxy раз это для лрп, то верни" ЛРП Бред" законы

Не, их точно запретили даже для мейна.

2024-12-01 12:14 UTC, Vonsant commented
Потому что мейн не лрп, а мрп сервер с пониженными требованиями.

2024-12-01 12:19 UTC, Vonsant commented
Потом если людям понравится, то будет переключено и на другие сервера, благо с цварниками просто работать.

2024-12-01 12:27 UTC, chavonadelal commented
> Потом если людям понравится, то будет переключено и на другие сервера, благо с цварниками просто работать.

там 0 онлайна, некому нравится будет

2024-12-01 12:27 UTC, chavonadelal commented
при том, что ивент с 20 онлайна только может выпасть, с меньшим онлайном в нем нет смысла

2024-12-04 12:56 UTC, FireNameFN requested changes

2024-12-04 12:56 UTC, FireNameFN commented on Content.Server/_CorvaxNext/StationEvents/Events/SpaceLawChange.cs
> +            var availableLaws = _sequenceLaws.Except(activeLaws).ToList();
```suggestion
            var availableLaws = _sequenceLaws.Except(activeLaws).ToArray();
```

2024-12-04 12:56 UTC, FireNameFN commented on Content.Server/_CorvaxNext/StationEvents/Events/SpaceLawChange.cs
> +            return;
```suggestion
                return;
```

2024-12-04 12:56 UTC, FireNameFN commented on Content.Server/_CorvaxNext/StationEvents/Events/SpaceLawChange.cs
> +        private List<string> GetActiveSpaceLaws()
Сделай через yield return.

2024-12-09 23:01 UTC, lzk228 requested changes
ревью кода только потому что я не хочу, чтобы вы мёржили какое-то говно
я не хочу чтобы это было мёржнуто вовсе, но МАКСИМАЛЬНО не хочу, пока:
- не будет добавлен способ для администрации и присоединившихся позже игроков узнать об изменённых законах СРАЗУ как только они присоединяются в раунд, я не буду предлагать как это делать, скажу лишь что это ОБЯЗАННО быть перед добавлением ивента в игру

2024-12-18 09:49 UTC, closed without merging